In [1]:
import codecs,unidecode,yaml,glob,re
import itertools as it
import pandas as pd

In [2]:
nQuizz=10
nAnnee=25
repQuizz="/Users/gilles/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/01-NotesQuizz/"
fQuizzoodle=repQuizz+"QuizzAll.csv"
fAliasQDLE=repQuizz+"Quizz-Alias.yaml"
fNotesOriginales=repQuizz+"%d-Quizz-Notes.xlsx"%nAnnee
fNotesFinales=repQuizz+"%d-Quizz-Notes-Finales.xlsx"%nAnnee
fCM=repQuizz+"CM.csv"

sep=u"\t"
nbQuestionQuizz={i:(7 if i<7 else 6) for i in range(1,nQuizz+1)}
nbQuestionQuizz

In [3]:
'''https://stackoverflow.com/a/35491326/3986209'''
def invert_dict(d): 
    inverse = dict() 
    for key in d: 
        # Go through the list that is saved in the dict:
        for item in d[key]:
            # Check if in the inverted dict the key exists
            if item not in inverse: 
                # If not create a new list
                inverse[item] = [key] 
            else: 
                inverse[item].append(key) 
    return inverse

# Fichier Etudiants

In [4]:
dfCM=pd.read_csv(filepath_or_buffer=fCM,sep="\t",encoding="utf8")
dfCM.columns

Index([u'Numéro d’identification', u'Nom de famille', u'Prénom',
       u'Adresse de courriel', u'Dernier téléchargement depuis ce cours'],
      dtype='object')

In [5]:
dfCM.set_index(u"Numéro d’identification",inplace=True)
dfCM[u"Code étudiant"]=dfCM.index.astype(unicode)
dfCM

,Nom de famille,Prénom,Adresse de courriel,Dernier téléchargement depuis ce cours,Code étudiant
Numéro d’identification,,,,,
455717,ABDALLAH TOMANY,SHAIMA,shaima.abdallah-tomany@etu.u-bordeaux-montaign...,1772291711,455717
429665,ABDELJALIL,LINA,lina.abdeljalil@etu.u-bordeaux-montaigne.fr,1772291711,429665
461076,AGGAR,LYDIA,lydia.aggar@etu.u-bordeaux-montaigne.fr,1772291711,461076
458113,AGLETINER,NELIA,nelia.agletiner@etu.u-bordeaux-montaigne.fr,1772291711,458113
396581,ALBON,LWANN,lwann.albon@etu.u-bordeaux-montaigne.fr,1772291711,396581
459692,ALMON,ADELIE,adelie.almon@etu.u-bordeaux-montaigne.fr,1772291711,459692
446215,ALTENOR,SERIANE,seriane.altenor@etu.u-bordeaux-montaigne.fr,1772291711,446215
435583,ANDRAC-PEPERMANS,NELL,nell.andrac-pepermans@etu.u-bordeaux-montaigne.fr,1772291711,435583
414295,ANDRADE,TIMOTHY,timothy.andrade@etu.u-bordeaux-montaigne.fr,1772291711,414295
461104,ANOGE,JULIA,julia.anoge@etu.u-bordeaux-montaigne.fr,1772291711,461104
458613,ARTOLA,CHLOE,chloe.artola@etu.u-bordeaux-montaigne.fr,1772291711,458613
441237,ATAM-KASSIGADOU,ELIZA,eliza.atam-kassigadou@etu.u-bordeaux-montaigne.fr,1772291711,441237
456651,AUGUSTE,MAELA,maela.auguste@etu.u-bordeaux-montaigne.fr,1772291711,456651
457795,BARBRY,LILY,lily.barbry@etu.u-bordeaux-montaigne.fr,1772291711,457795
445372,BARBU,MATEI-TEODOR,matei-teodor.barbu@etu.u-bordeaux-montaigne.fr,1772291711,445372
460351,BELFERKOUS,MAISSA,maissa.belferkous@etu.u-bordeaux-montaigne.fr,1772291711,460351
434036,BENAOUDIA,AHCENE,ahcene.benaoudia@etu.u-bordeaux-montaigne.fr,1772291711,434036
457173,BESSONART,MATHILDE,mathilde.bessonart@etu.u-bordeaux-montaigne.fr,1772291711,457173
460714,BLANC,LAURINE,laurine.blanc@etu.u-bordeaux-montaigne.fr,1772291711,460714
458790,BLANCHARD,ANDREA,andrea.blanchard@etu.u-bordeaux-montaigne.fr,1772291711,458790
454875,BONETBELTS,ANAIS,anais.bonetbelts@etu.u-bordeaux-montaigne.fr,1772291711,454875
460512,BOUIN,VALENTINE,valentine.bouin@etu.u-bordeaux-montaigne.fr,1772291711,460512
458727,BOURCHACHENE,LINA,lina.bourchachene@etu.u-bordeaux-montaigne.fr,1772291711,458727
416701,BOUREMA,OMEIMA,omeima.bourema@etu.u-bordeaux-montaigne.fr,1772291711,416701
450856,CAID ESSEBSI,NOUR,nour.caid-essebsi@etu.u-bordeaux-montaigne.fr,1772291711,450856
458609,CALLEDE,NINA,nina.callede@etu.u-bordeaux-montaigne.fr,1772291711,458609
459964,CAMBARRAT,MARGAUX,margaux.cambarrat@etu.u-bordeaux-montaigne.fr,1772291711,459964
446384,CAMUT,JULIETTE,juliette.camut@etu.u-bordeaux-montaigne.fr,1772291711,446384
456710,CANLI,SEMA,sema.canli@etu.u-bordeaux-montaigne.fr,1772291711,456710
457965,CAPRAJA,LILA,lila.capraja@etu.u-bordeaux-montaigne.fr,1772291711,457965
...,...,...,...,...,...
460309,POINSOT,KATHLEEN,kathleen.poinsot@etu.u-bordeaux-montaigne.fr,1772291711,460309
459745,POULET--CONSTANTIN,ANNA,anna.poulet--constantin@etu.u-bordeaux-montaig...,1772291711,459745
454341,POVEDA-DURASTANTI,MAELLE,maelle.poveda-durastanti@etu.u-bordeaux-montai...,1772291711,454341
458341,PREVOT,EMMA,emma.prevot@etu.u-bordeaux-montaigne.fr,1772291711,458341
462574,PRISCA VAVY,SIMONE,simone.prisca-vavy@etu.u-bordeaux-montaigne.fr,1772291711,462574
458209,QARTIT,SHAIMA,shaima.qartit@etu.u-bordeaux-montaigne.fr,1772291711,458209
457340,RAFFALLI,MARIE-DIANE,marie-diane.raffalli@etu.u-bordeaux-montaigne.fr,1772291711,457340
461334,RAHARIJAONA,MIARANA HAMY FITAHIA,miarana-hamy-fitahia.raharijaona@etu.u-bordeau...,1772291711,461334
460054,RAOULT--DESTOUR,ARTEMIS,artemis.raoult--destour@etu.u-bordeaux-montaig...,1772291711,460054
426755,RECULET,MARIUS,marius.reculet@etu.u-bordeaux-montaigne.fr,1772291711,426755
458667,RHODE,MANON,manon.rhode@etu.u-bordeaux-montaigne.fr,1772291711,458667
450931,RIAUD,MELISSANDRE,melissandre.riaud@etu.u-bordeaux-montaigne.fr,1772291711,450931
458319,RICHAUD,CHLOE,chloe.richaud@etu.u-bordeaux-montaigne.fr,1772291711,458319
461303,RICHAUME,JULIEN,julien.richaume@etu.u-bordeaux-montaigne.fr,1772291711,461303
441018,RIVIERE,LUCIE,lucie.riviere1@etu.u-bordeaux-montaigne.fr,1772291711,441018
458551,ROBIN--DEGUIL,ALAIA,alaia.robin--deguil@etu.u-bordeaux-montaigne.fr,1772291711,458551
461847,ROUYAT,KAMERON,kameron.rouyat@etu.u-bordeaux-montaigne.fr,1772291711,461847
454123,SAIDI,NOUHAILA,nouhaila.saidi@etu.u-bordeaux-montaigne.fr,1772291711,454123
455153,SAIS,ROXANE,roxane.sais@etu.u-bordeaux-montaigne.fr,1772291711,455153
382568,SAUZE,THOMAS,thomas.sauze@etu.u-bordeaux-montaigne.fr,1772291711,382568
460084,SEYDI,COPPELIA,coppelia.seydi@etu.u-bordeaux-montaigne.fr,1772291711,460084
446347,SIGISCAR,CANDYCE,candyce.sigiscar@etu.u-bordeaux-montaigne.fr,1772291711,446347
459660,SOUCHET,BEATRICE,beatrice.souchet@etu.u-bordeaux-montaigne.fr,1772291711,459660
458747,SPECOGNA,ELISA,elisa.specogna@etu.u-bordeaux-montaigne.fr,1772291711,458747
460488,STIDLER,ADELE,adele.stidler@etu.u-bordeaux-montaigne.fr,1772291711,460488
457363,TANG,YING CHEUNG,ying-cheung.tang@etu.u-bordeaux-montaigne.fr,1772291711,457363
459756,TIXIER,AMELYNE,amelyne.tixier@etu.u-bordeaux-montaigne.fr,1772291711,459756
453907,VAGNER,CORALIE,coralie.vagner@etu.u-bordeaux-montaigne.fr,1772291711,453907
460525,ZAHI,NASSIM,nassim.zahi@etu.u-bordeaux-montaigne.fr,1772291711,460525
460114,ZAIRI,NAOMIE,naomie.zairi@etu.u-bordeaux-montaigne.fr,1772291711,460114

# Fichier Alias

In [6]:
try:
    with codecs.open(fAliasQDLE, 'r', encoding="utf8") as inputfile:
        correspondances=yaml.safe_load(inputfile)
    alias=correspondances["alias2etu"]
except:
    alias={}
alias

{u'Ad\xe8le-stidler': ['460488'],
 u'Ad\xe8le.Stidler': ['460488'],
 u'Ad\xe9lie Almon-Juliette Camut': ['459692', '446384'],
 u'Ad\xe9lie Qlmon': ['459692'],
 u'Ad\xe9lie-Almon': ['459692'],
 u'Ad\xe9lie-Almon Juliette-Camut': ['459692', '446384'],
 'Ahcene': ['434036'],
 u'Ala\xefa': ['458551'],
 u'Ala\xefa / Le\xefla': ['458551', '458391'],
 u'Ala\xefa RD / Le\xefla Facon': ['458551', '458391'],
 u'Ala\xefa Robin Deguil': ['458551'],
 'Albanne Pagnoux-Pellegrino': ['460344'],
 'Anais-manus': ['457731'],
 u'Ana\xebl': ['453951'],
 u'Andr\xe9a': ['458790'],
 u'B\xe9a': ['459660'],
 'Charlotte-mariagecornille': ['453211'],
 u'Chlo\xe9- Cartigny': ['453789'],
 u'Copp\xe9lia SEYDI': ['460084'],
 u'Copp\xe9lia seydi': ['460084'],
 u'Copp\xe9lia-SEYDI': ['460084'],
 'Dupouy-Leonie': ['456690'],
 'Eleonore Courtot': ['459136'],
 'Eleonore/mathildemajerus': ['459136', '458207'],
 'EleonorecourtotMathildemajerus': ['459136', '458207'],
 'Elisa Lavielle': ['458324'],
 'Elisa Lucante': ['457483'],
 'Elisa Specogna': ['458747'],
 'Elisa-Fougere': ['463682'],
 'Elisa-Specogna': ['458747'],
 'Elisa-Specogna,  emma darricau': ['458747', '458313'],
 'Emma Darricau': ['458313'],
 'Emma darricau': ['458313'],
 'Emma darricau-Delhay- Pelanne': ['458313', '458356', '458010'],
 'Fevre Faustine': ['456672'],
 'GUETATFA Ilhem': ['447671'],
 'Giulia Nisini': ['463562'],
 'Joakim-Lubin': ['457111'],
 'Julia-Anoge-Elsa-Dumas': ['461104', '461325'],
 'Juliette-camut': ['446384'],
 'Juliette-camut Lila-Capraja': ['446384', '457965'],
 u'Juliette-camut M\xe9li-riaud': ['446384', '450931'],
 u'J\xe9r\xe9mie Dubois': ['459971'],
 u'J\xe9r\xe9mie-Dubois': ['459971'],
 'Kameron rouyat': ['461847'],
 'Leonie Dupuy': ['456690'],
 'Lila-Capraja': ['457965'],
 'Lina-Bourchachene': ['458727'],
 'Louhane.crowin': ['453815'],
 'Lubin Joakim': ['457111'],
 u'L\xe9onie-Dupouy': ['456690'],
 'Maela-Auguste': ['456651'],
 'Maela-auguste': ['456651'],
 'Maelle': ['454341'],
 u'Maena Lamolere\u2014Phelep': ['457961'],
 'Mame-Diop': ['462309'],
 'Manon-RHODE': ['458667'],
 'Manon-freyche': ['457558'],
 'Mathieu-Monteille': ['454079'],
 'Mathilde Bessonart': ['457173'],
 'Mathilde Majerus': ['458207'],
 u'Ma\xe9ly-LE TOUARIN CARVALHO': ['457714'],
 u'Ma\xe9ly.LeTouarinCarvalho': ['457714'],
 u'Ma\xebna -Lamol\xe8re Phelep': ['457961'],
 'Mignardot-Tiphaine': ['456686'],
 u'M\xe9lanie Lassagne': ['430746'],
 u'M\xe9lanie.lassagne': ['430746'],
 u'M\xe9li-Riaud.Juliette-Camut': ['450931', '446384'],
 u'M\xe9lissandre-Riaud': ['450931'],
 'Nassim Zahi': ['460525'],
 'Nicolo Farris - Giulia Nisini': ['463519', '463562'],
 'Nina callede , roxane Sais': ['458609', '455153'],
 u'Nina callede, roxane Sa\xefs': ['458609', '455153'],
 'Oceane-defreitas': ['458657'],
 u'Ome\xefma': ['416701'],
 u'Ome\xefma-Bourema': ['416701'],
 'Pagnoux Albanne': ['460344'],
 'Pagnoux-Pellegrino-Albanne': ['460344'],
 'Prep-prep': ['459660'],
 'Rhode-Manon': ['458667'],
 'Roxane sais, nina callede': ['455153', '458609'],
 'Roxane,Nina': ['455153', '458609'],
 'Sannah MAURINIER': ['460392'],
 'Sema': ['456710'],
 'Sema-Canli': ['456710'],
 'Simone_PRISCA_VAVY': ['462574'],
 'Simone_prisca_vavy': ['462574'],
 'Timothee carrasset': ['455667'],
 'Timothee-carrasset': ['455667'],
 'Tiphaine Mignardot': ['456686'],
 'Tiphaine-Mignardot': ['456686'],
 'Victoria-Delhay Lucia-Pelanne': ['458356', '458010'],
 'Victoria-delhay': ['458356'],
 'Victoria-delhay Lucia-Pelanne': ['458356', '458010'],
 'Yuna-Gicquel': ['456846'],
 'Yuna-Gicquel. Adelie-almon': ['456846', '459692'],
 u'Yuna-Gicquel. Ad\xe9lie.Almon': ['456846', '459692'],
 u'Yuna-Gicquel.Ad\xe9lie-Almon': ['456846', '459692'],
 'albon lwann': ['396581'],
 'anais - bonetbelts': ['454875'],
 'anais-manus': ['457731'],
 'anais.bonetbelts': ['454875'],
 'camille-pelloquin': ['456868'],
 u'chlo\xe9-artola': ['458613'],
 'elisa-specogna': ['458747'],
 'hortense': ['458329'],
 'hortense-delacou': ['458329'],
 'ingrid fletcher': ['463523'],
 'jeane gabaston': ['460874'],
 'justine-loustaunau': ['459959'],
 'lana': ['460037'],
 'lena-erc': ['460829'],
 'lily barbry': ['457795'],
 'louhane-crowin': ['453815'],
 'louise dutheil': ['449639'],
 'louise-laveau': ['457952'],
 u'louise-laveau m\xe9lanie.lassagne': ['457952', '430746'],
 'louise.laveau': ['457952'],
 'lucie riviere': ['441018'],
 'lwann-albon': ['396581'],
 'maela-auguste': ['456651'],
 'maela.auguste': ['456651'],
 'manon-olivier': ['454852'],
 'melissa-johannet': ['455719'],
 'milena-hamilton': ['452779'],
 'mintou_ndiaye': ['460169'],
 u'n\xe9lia-agletiner': ['458113'],
 'rihanna - lair': ['456402'],
 u'roxane Sa\xefs, Nina callede': ['455153', '458609'],
 'sarah guellil': ['461900'],
 'sarah-guellil': ['461900'],
 'sema': ['456710'],
 'timothee-carrasset': ['455667'],
 'timothy andrade': ['414295'],
 'timothy-andradE': ['414295'],
 'timothy-andrade': ['414295'],
 u'timoth\xe9e-carrasset': ['455667'],
 'victoria-delhay': ['458356'],
 u'zo\xe9-marostica': ['453892'],
 u'\xe9lisa-coureau': ['459406'],
 u'\xe9lisa-coureau. manon-rhode': ['459406', '458667'],
 u'\xe9lisa_coureau': ['459406']}

In [13]:
colCM=[u"id",u"nom",u"prénom",u"email",u"ine"]
# colQuizz=["pseudo","points","temps"]

try:
    dfCM=pd.read_csv(fCM,sep="\t",encoding="utf8",header=0,names=colCM)
    lQuizz=pd.read_csv(fQuizzoodle,sep=";",encoding="utf8",header=0)
    lQuizz.columns=["pseudo"]+lQuizz.columns.tolist()[1:]
    # lQuizz.pseudo=lQuizz.pseudo.str.strip()
except:
    dfCM=None
    lQuizz=None

In [14]:
# lQuizz=pd.read_csv(fQuizzoodle,sep=";",encoding="utf8",header=0)
lQuizz

,pseudo,0(2),1(4),2(6),3(9),4(11),5(13),6(16),7(18),8(20),...,20(48),21(51),22(53),23(55),24(58),25(60),26(62),27(65),28(67),29(69)
0,,E,F,G,B,A,D,B,A,A,...,D,B,A,D,B,C,D,D,B,A
1,albon lwann,D,F,F,D,A,A,A,A,A,...,D,D,B,C,C,C,B,C,B,C
2,Juliette-camut,?,?,?,?,?,?,?,B,B,...,D,B,D,D,D,C,D,B,A,A
3,Mélanie,?,?,?,A,D,B,A,?,B,...,B,B,A,B,A,C,D,D,?,D
4,melissa.johannet,?,?,?,B,A,C,D,?,B,...,D,C,C,D,B,B,?,A,A,D
5,nélia-agletiner,?,?,?,A,B,B,B,C,B,...,B,B,A,C,A,C,C,D,B,D
6,louise.laveau,?,?,?,A,?,B,B,C,B,...,B,B,A,C,A,C,D,A,B,D
7,manon-olivier,?,?,?,B,D,B,D,B,B,...,D,D,D,D,?,B,B,A,B,A
8,Mélissandre-Riaud,?,F,G,A,D,B,B,A,B,...,D,?,D,D,B,C,D,?,C,A
9,Lubin-Joakim,F,F,?,D,A,D,B,A,B,...,B,C,A,B,A,C,D,B,B,A
10,Madi,G,E,E,B,D,B,B,B,A,...,D,A,D,B,?,?,?,C,B,D
11,Fevre Faustine,E,D,G,D,A,C,C,A,B,...,B,B,A,D,B,D,B,A,B,C
12,Adélie-Almon,E,F,G,A,D,B,B,?,B,...,D,C,D,C,A,C,D,B,C,A
13,Yuna-Gicquel,E,F,G,A,D,B,B,B,B,...,D,B,D,B,A,C,?,B,A,A
14,Oceane-defreitas,E,F,G,D,A,C,C,B,B,...,B,B,A,D,B,B,C,C,B,C
15,Dupouy-Leonie,F,F,G,D,A,D,B,A,B,...,B,C,A,B,A,C,D,B,B,A
16,rivière lucie,E,D,G,D,A,C,C,A,B,...,D,C,C,D,B,B,?,A,A,D
17,Maély.LeTouarinCarvalho,E,F,D,B,A,C,C,A,B,...,D,A,D,B,A,B,C,D,D,A
18,Adèle.Stidler,E,F,D,D,A,C,B,A,B,...,C,B,A,D,A,?,D,A,A,A
19,Elisa Lucante,E,F,F,D,A,B,A,A,B,...,D,D,D,A,D,B,B,B,A,D
20,Elisa Specogna,D,F,G,D,A,B,A,?,B,...,D,B,D,D,C,A,D,B,C,D
21,timothy-andrade,E,F,G,B,A,D,C,F,A,...,B,C,B,D,C,C,B,D,C,A
22,Mira,?,?,?,?,?,?,?,?,?,...,?,?,?,?,?,?,?,?,?,?
23,louhane-crowin,F,D,G,D,A,C,A,B,A,...,C,D,B,D,C,C,C,?,B,C
24,anais-manus,E,E,G,C,C,A,D,C,A,...,D,B,C,D,B,A,?,D,A,C
25,maela-auguste,E,B,G,B,C,B,D,A,A,...,D,B,C,B,B,C,D,B,A,C
26,simone_prisca_vavy,E,B,G,B,C,B,D,F,A,...,D,B,D,B,A,A,D,D,A,A
27,chloé-artola,F,D,D,A,A,D,C,A,A,...,C,B,A,D,C,C,D,A,C,B
28,Jérémie Dubois,D,F,D,B,D,D,B,A,B,...,D,A,D,B,A,C,D,C,A,C
29,Coppélia-SEYDI,D,D,G,D,D,B,B,A,A,...,D,B,B,D,B,C,C,B,B,A
30,Alaïa,D,F,G,D,B,D,C,A,B,...,?,?,?,?,?,?,?,?,?,?
31,Maena Lamolere—Phelep,F,D,?,D,A,A,A,D,A,...,B,D,B,C,C,C,B,?,D,C
32,milena-hamilton,E,A,F,D,A,B,D,A,A,...,D,C,A,D,C,C,C,C,A,C
33,Mathieu-Monteille,E,F,G,B,A,C,C,A,?,...,D,B,A,B,A,C,?,C,C,A

In [15]:
dfCM["PN"]=dfCM[u"prénom"].str.lower().str.strip()+" "+dfCM[u"nom"].str.lower().str.strip()
dfCM["NP"]=dfCM[u"nom"].str.lower().str.strip()+" "+dfCM[u"prénom"].str.lower().str.strip()

In [16]:
lQuizz

,pseudo,0(2),1(4),2(6),3(9),4(11),5(13),6(16),7(18),8(20),...,20(48),21(51),22(53),23(55),24(58),25(60),26(62),27(65),28(67),29(69)
0,,E,F,G,B,A,D,B,A,A,...,D,B,A,D,B,C,D,D,B,A
1,albon lwann,D,F,F,D,A,A,A,A,A,...,D,D,B,C,C,C,B,C,B,C
2,Juliette-camut,?,?,?,?,?,?,?,B,B,...,D,B,D,D,D,C,D,B,A,A
3,Mélanie,?,?,?,A,D,B,A,?,B,...,B,B,A,B,A,C,D,D,?,D
4,melissa.johannet,?,?,?,B,A,C,D,?,B,...,D,C,C,D,B,B,?,A,A,D
5,nélia-agletiner,?,?,?,A,B,B,B,C,B,...,B,B,A,C,A,C,C,D,B,D
6,louise.laveau,?,?,?,A,?,B,B,C,B,...,B,B,A,C,A,C,D,A,B,D
7,manon-olivier,?,?,?,B,D,B,D,B,B,...,D,D,D,D,?,B,B,A,B,A
8,Mélissandre-Riaud,?,F,G,A,D,B,B,A,B,...,D,?,D,D,B,C,D,?,C,A
9,Lubin-Joakim,F,F,?,D,A,D,B,A,B,...,B,C,A,B,A,C,D,B,B,A
10,Madi,G,E,E,B,D,B,B,B,A,...,D,A,D,B,?,?,?,C,B,D
11,Fevre Faustine,E,D,G,D,A,C,C,A,B,...,B,B,A,D,B,D,B,A,B,C
12,Adélie-Almon,E,F,G,A,D,B,B,?,B,...,D,C,D,C,A,C,D,B,C,A
13,Yuna-Gicquel,E,F,G,A,D,B,B,B,B,...,D,B,D,B,A,C,?,B,A,A
14,Oceane-defreitas,E,F,G,D,A,C,C,B,B,...,B,B,A,D,B,B,C,C,B,C
15,Dupouy-Leonie,F,F,G,D,A,D,B,A,B,...,B,C,A,B,A,C,D,B,B,A
16,rivière lucie,E,D,G,D,A,C,C,A,B,...,D,C,C,D,B,B,?,A,A,D
17,Maély.LeTouarinCarvalho,E,F,D,B,A,C,C,A,B,...,D,A,D,B,A,B,C,D,D,A
18,Adèle.Stidler,E,F,D,D,A,C,B,A,B,...,C,B,A,D,A,?,D,A,A,A
19,Elisa Lucante,E,F,F,D,A,B,A,A,B,...,D,D,D,A,D,B,B,B,A,D
20,Elisa Specogna,D,F,G,D,A,B,A,?,B,...,D,B,D,D,C,A,D,B,C,D
21,timothy-andrade,E,F,G,B,A,D,C,F,A,...,B,C,B,D,C,C,B,D,C,A
22,Mira,?,?,?,?,?,?,?,?,?,...,?,?,?,?,?,?,?,?,?,?
23,louhane-crowin,F,D,G,D,A,C,A,B,A,...,C,D,B,D,C,C,C,?,B,C
24,anais-manus,E,E,G,C,C,A,D,C,A,...,D,B,C,D,B,A,?,D,A,C
25,maela-auguste,E,B,G,B,C,B,D,A,A,...,D,B,C,B,B,C,D,B,A,C
26,simone_prisca_vavy,E,B,G,B,C,B,D,F,A,...,D,B,D,B,A,A,D,D,A,A
27,chloé-artola,F,D,D,A,A,D,C,A,A,...,C,B,A,D,C,C,D,A,C,B
28,Jérémie Dubois,D,F,D,B,D,D,B,A,B,...,D,A,D,B,A,C,D,C,A,C
29,Coppélia-SEYDI,D,D,G,D,D,B,B,A,A,...,D,B,B,D,B,C,C,B,B,A
30,Alaïa,D,F,G,D,B,D,C,A,B,...,?,?,?,?,?,?,?,?,?,?
31,Maena Lamolere—Phelep,F,D,?,D,A,A,A,D,A,...,B,D,B,C,C,C,B,?,D,C
32,milena-hamilton,E,A,F,D,A,B,D,A,A,...,D,C,A,D,C,C,C,C,A,C
33,Mathieu-Monteille,E,F,G,B,A,C,C,A,?,...,D,B,A,B,A,C,?,C,C,A

In [17]:
pseudos=lQuizz[~(lQuizz["pseudo"].isin(alias))]["pseudo"].str.strip().tolist()
print "\n".join(pseudos)

Mélanie
melissa.johannet
Lubin-Joakim
Madi
rivière lucie
Mira
simone_prisca_vavy

In [18]:
for nP,pseudo in enumerate(pseudos):
    print pseudo
    sPseudo = raw_input("Nom a chercher:\n")
    if sPseudo:
        print dfCM[dfCM["PN"].str.contains(sPseudo.lower())][["PN","id"]]
        idPseudo=raw_input("id :\n")
        if idPseudo:
            alias[pseudo]=idPseudo

Nom a chercher:

Mélanie

Nom a chercher:
 mélanie

Empty DataFrame
Columns: [PN, id]
Index: []

id :
 430746

melissa.johannet

Nom a chercher:
 johann

                  PN      id
89  melissa johannet  455719

id :
 455719

Lubin-Joakim

Nom a chercher:
 Lubin

               PN      id
106  joakim lubin  457111

id :
 457111

Madi

Nom a chercher:
 madi

               PN      id
108  khalida madi  460583

id :
 460583

rivière lucie

Nom a chercher:
 riviere

                PN      id
146  lucie riviere  441018

id :
 441018

Mira

Nom a chercher:
 mira

                     PN      id
86  jay-mira irangabiye  461111

id :
 461111

simone_prisca_vavy

Nom a chercher:
 prisca

                     PN      id
136  simone prisca vavy  462574

id :
 462574

In [19]:
# pseudo=u"Cotentin, Pailhes"
# alias[pseudo]=["414180","411916"]

In [20]:
sPseudo="pailh"
print dfCM[dfCM["PN"].str.contains(sPseudo.lower())][["PN","id"]]

Empty DataFrame
Columns: [PN, id]
Index: []

In [21]:
pn=dfCM["PN"].tolist()
np=dfCM["NP"].tolist()

In [22]:
for pseudo in pseudos:
    if unidecode.unidecode(pseudo.lower()) in pn:
        print pseudo,dfCM[dfCM["PN"]==unidecode.unidecode(pseudo.lower())]["id"].values[0]
        alias[pseudo]=[str(dfCM[dfCM["PN"]==unidecode.unidecode(pseudo.lower())]["id"].values[0])]
    elif unidecode.unidecode(pseudo.lower()) in np:
        print pseudo,dfCM[dfCM["NP"]==unidecode.unidecode(pseudo.lower())]["id"].values[0]
        alias[pseudo]=[str(dfCM[dfCM["NP"]==unidecode.unidecode(pseudo.lower())]["id"].values[0])]

rivière lucie 441018

In [23]:
for al in alias:
    if not isinstance(alias[al],list):
        if " " in alias[al]:
            alias[al]=alias[al].split(" ")
        else:
            alias[al]=[alias[al]]

for k,v in alias.iteritems():
    if " " in v[0]:
        print k,v
        # alias[k]=v[0].split(" ")

In [24]:
invAlias=invert_dict(alias)
#invAlias[385732]=[u'adiarra001, cbeauvais004']
correspondances={"alias2etu":alias,"etu2alias":invAlias}
correspondances

{'alias2etu': {u'Ad\xe8le-stidler': ['460488'],
  u'Ad\xe8le.Stidler': ['460488'],
  u'Ad\xe9lie Almon-Juliette Camut': ['459692', '446384'],
  u'Ad\xe9lie Qlmon': ['459692'],
  u'Ad\xe9lie-Almon': ['459692'],
  u'Ad\xe9lie-Almon Juliette-Camut': ['459692', '446384'],
  'Ahcene': ['434036'],
  u'Ala\xefa': ['458551'],
  u'Ala\xefa / Le\xefla': ['458551', '458391'],
  u'Ala\xefa RD / Le\xefla Facon': ['458551', '458391'],
  u'Ala\xefa Robin Deguil': ['458551'],
  'Albanne Pagnoux-Pellegrino': ['460344'],
  'Anais-manus': ['457731'],
  u'Ana\xebl': ['453951'],
  u'Andr\xe9a': ['458790'],
  u'B\xe9a': ['459660'],
  'Charlotte-mariagecornille': ['453211'],
  u'Chlo\xe9- Cartigny': ['453789'],
  u'Copp\xe9lia SEYDI': ['460084'],
  u'Copp\xe9lia seydi': ['460084'],
  u'Copp\xe9lia-SEYDI': ['460084'],
  'Dupouy-Leonie': ['456690'],
  'Eleonore Courtot': ['459136'],
  'Eleonore/mathildemajerus': ['459136', '458207'],
  'EleonorecourtotMathildemajerus': ['459136', '458207'],
  'Elisa Lavielle': ['458324'],
  'Elisa Lucante': ['457483'],
  'Elisa Specogna': ['458747'],
  'Elisa-Fougere': ['463682'],
  'Elisa-Specogna': ['458747'],
  'Elisa-Specogna,  emma darricau': ['458747', '458313'],
  'Emma Darricau': ['458313'],
  'Emma darricau': ['458313'],
  'Emma darricau-Delhay- Pelanne': ['458313', '458356', '458010'],
  'Fevre Faustine': ['456672'],
  'GUETATFA Ilhem': ['447671'],
  'Giulia Nisini': ['463562'],
  'Joakim-Lubin': ['457111'],
  'Julia-Anoge-Elsa-Dumas': ['461104', '461325'],
  'Juliette-camut': ['446384'],
  'Juliette-camut Lila-Capraja': ['446384', '457965'],
  u'Juliette-camut M\xe9li-riaud': ['446384', '450931'],
  u'J\xe9r\xe9mie Dubois': ['459971'],
  u'J\xe9r\xe9mie-Dubois': ['459971'],
  'Kameron rouyat': ['461847'],
  'Leonie Dupuy': ['456690'],
  'Lila-Capraja': ['457965'],
  'Lina-Bourchachene': ['458727'],
  'Louhane.crowin': ['453815'],
  'Lubin Joakim': ['457111'],
  u'Lubin-Joakim': ['457111'],
  u'L\xe9onie-Dupouy': ['456690'],
  u'Madi': ['460583'],
  'Maela-Auguste': ['456651'],
  'Maela-auguste': ['456651'],
  'Maelle': ['454341'],
  u'Maena Lamolere\u2014Phelep': ['457961'],
  'Mame-Diop': ['462309'],
  'Manon-RHODE': ['458667'],
  'Manon-freyche': ['457558'],
  'Mathieu-Monteille': ['454079'],
  'Mathilde Bessonart': ['457173'],
  'Mathilde Majerus': ['458207'],
  u'Ma\xe9ly-LE TOUARIN CARVALHO': ['457714'],
  u'Ma\xe9ly.LeTouarinCarvalho': ['457714'],
  u'Ma\xebna -Lamol\xe8re Phelep': ['457961'],
  'Mignardot-Tiphaine': ['456686'],
  u'Mira': ['461111'],
  u'M\xe9lanie': ['430746'],
  u'M\xe9lanie Lassagne': ['430746'],
  u'M\xe9lanie.lassagne': ['430746'],
  u'M\xe9li-Riaud.Juliette-Camut': ['450931', '446384'],
  u'M\xe9lissandre-Riaud': ['450931'],
  'Nassim Zahi': ['460525'],
  'Nicolo Farris - Giulia Nisini': ['463519', '463562'],
  'Nina callede , roxane Sais': ['458609', '455153'],
  u'Nina callede, roxane Sa\xefs': ['458609', '455153'],
  'Oceane-defreitas': ['458657'],
  u'Ome\xefma': ['416701'],
  u'Ome\xefma-Bourema': ['416701'],
  'Pagnoux Albanne': ['460344'],
  'Pagnoux-Pellegrino-Albanne': ['460344'],
  'Prep-prep': ['459660'],
  'Rhode-Manon': ['458667'],
  'Roxane sais, nina callede': ['455153', '458609'],
  'Roxane,Nina': ['455153', '458609'],
  'Sannah MAURINIER': ['460392'],
  'Sema': ['456710'],
  'Sema-Canli': ['456710'],
  'Simone_PRISCA_VAVY': ['462574'],
  'Simone_prisca_vavy': ['462574'],
  'Timothee carrasset': ['455667'],
  'Timothee-carrasset': ['455667'],
  'Tiphaine Mignardot': ['456686'],
  'Tiphaine-Mignardot': ['456686'],
  'Victoria-Delhay Lucia-Pelanne': ['458356', '458010'],
  'Victoria-delhay': ['458356'],
  'Victoria-delhay Lucia-Pelanne': ['458356', '458010'],
  'Yuna-Gicquel': ['456846'],
  'Yuna-Gicquel. Adelie-almon': ['456846', '459692'],
  u'Yuna-Gicquel. Ad\xe9lie.Almon': ['456846', '459692'],
  u'Yuna-Gicquel.Ad\xe9lie-Almon': ['456846', '459692'],
  'albon lwann': ['396581'],
  'anais - bonetbelts': ['454875'],
  'anais-manus': ['457731'],
  'anais.bonetbelts': ['454875'],
  'camille-pelloquin': ['456868'],
  u'chlo\xe9-artola': ['458613'],
  'elisa-specogna': ['458747'],
  'hortense': ['458329'],
  'hortense-delacou': ['458329'],
  'ingrid fletcher': ['463523'],
  'jeane gabaston': ['460874'],
  'justine-loustaunau': ['459959'],
  'lana': ['460037'],
  'lena-erc': ['460829'],
  'lily barbry': ['457795'],
  'louhane-crowin': ['453815'],
  'louise dutheil': ['449639'],
  'louise-laveau': ['457952'],
  u'louise-laveau m\xe9lanie.lassagne': ['457952', '430746'],
  'louise.laveau': ['457952'],
  'lucie riviere': ['441018'],
  'lwann-albon': ['396581'],
  'maela-auguste': ['456651'],
  'maela.auguste': ['456651'],
  'manon-olivier': ['454852'],
  'melissa-johannet': ['455719'],
  u'melissa.johannet': ['455719'],
  'milena-hamilton': ['452779'],
  'mintou_ndiaye': ['460169'],
  u'n\xe9lia-agletiner': ['458113'],
  'rihanna - lair': ['456402'],
  u'rivi\xe8re lucie': ['441018'],
  u'roxane Sa\xefs, Nina callede': ['455153', '458609'],
  'sarah guellil': ['461900'],
  'sarah-guellil': ['461900'],
  'sema': ['456710'],
  u'simone_prisca_vavy': ['462574'],
  'timothee-carrasset': ['455667'],
  'timothy andrade': ['414295'],
  'timothy-andradE': ['414295'],
  'timothy-andrade': ['414295'],
  u'timoth\xe9e-carrasset': ['455667'],
  'victoria-delhay': ['458356'],
  u'zo\xe9-marostica': ['453892'],
  u'\xe9lisa-coureau': ['459406'],
  u'\xe9lisa-coureau. manon-rhode': ['459406', '458667'],
  u'\xe9lisa_coureau': ['459406']},
 'etu2alias': {'396581': ['albon lwann', 'lwann-albon'],
  '414295': ['timothy-andrade', 'timothy-andradE', 'timothy andrade'],
  '416701': [u'Ome\xefma', u'Ome\xefma-Bourema'],
  '430746': [u'louise-laveau m\xe9lanie.lassagne',
   u'M\xe9lanie Lassagne',
   u'M\xe9lanie',
   u'M\xe9lanie.lassagne'],
  '434036': ['Ahcene'],
  '441018': [u'rivi\xe8re lucie', 'lucie riviere'],
  '446384': [u'M\xe9li-Riaud.Juliette-Camut',
   u'Ad\xe9lie Almon-Juliette Camut',
   'Juliette-camut Lila-Capraja',
   u'Ad\xe9lie-Almon Juliette-Camut',
   u'Juliette-camut M\xe9li-riaud',
   'Juliette-camut'],
  '447671': ['GUETATFA Ilhem'],
  '449639': ['louise dutheil'],
  '450931': [u'M\xe9li-Riaud.Juliette-Camut',
   u'Juliette-camut M\xe9li-riaud',
   u'M\xe9lissandre-Riaud'],
  '452779': ['milena-hamilton'],
  '453211': ['Charlotte-mariagecornille'],
  '453789': [u'Chlo\xe9- Cartigny'],
  '453815': ['Louhane.crowin', 'louhane-crowin'],
  '453892': [u'zo\xe9-marostica'],
  '453951': [u'Ana\xebl'],
  '454079': ['Mathieu-Monteille'],
  '454341': ['Maelle'],
  '454852': ['manon-olivier'],
  '454875': ['anais.bonetbelts', 'anais - bonetbelts'],
  '455153': ['Roxane,Nina',
   u'roxane Sa\xefs, Nina callede',
   'Nina callede , roxane Sais',
   'Roxane sais, nina callede',
   u'Nina callede, roxane Sa\xefs'],
  '455667': ['Timothee-carrasset',
   'timothee-carrasset',
   u'timoth\xe9e-carrasset',
   'Timothee carrasset'],
  '455719': ['melissa-johannet', u'melissa.johannet'],
  '456402': ['rihanna - lair'],
  '456651': ['Maela-Auguste',
   'maela-auguste',
   'Maela-auguste',
   'maela.auguste'],
  '456672': ['Fevre Faustine'],
  '456686': ['Tiphaine-Mignardot', 'Mignardot-Tiphaine', 'Tiphaine Mignardot'],
  '456690': [u'L\xe9onie-Dupouy', 'Leonie Dupuy', 'Dupouy-Leonie'],
  '456710': ['sema', 'Sema-Canli', 'Sema'],
  '456846': [u'Yuna-Gicquel. Ad\xe9lie.Almon',
   u'Yuna-Gicquel.Ad\xe9lie-Almon',
   'Yuna-Gicquel',
   'Yuna-Gicquel. Adelie-almon'],
  '456868': ['camille-pelloquin'],
  '457111': ['Joakim-Lubin', 'Lubin Joakim', u'Lubin-Joakim'],
  '457173': ['Mathilde Bessonart'],
  '457483': ['Elisa Lucante'],
  '457558': ['Manon-freyche'],
  '457714': [u'Ma\xe9ly.LeTouarinCarvalho', u'Ma\xe9ly-LE TOUARIN CARVALHO'],
  '457731': ['anais-manus', 'Anais-manus'],
  '457795': ['lily barbry'],
  '457952': [u'louise-laveau m\xe9lanie.lassagne',
   'louise.laveau',
   'louise-laveau'],
  '457961': [u'Maena Lamolere\u2014Phelep', u'Ma\xebna -Lamol\xe8re Phelep'],
  '457965': ['Juliette-camut Lila-Capraja', 'Lila-Capraja'],
  '458010': ['Victoria-Delhay Lucia-Pelanne',
   'Emma darricau-Delhay- Pelanne',
   'Victoria-delhay Lucia-Pelanne'],
  '458113': [u'n\xe9lia-agletiner'],
  '458207': ['Mathilde Majerus',
   'EleonorecourtotMathildemajerus',
   'Eleonore/mathildemajerus'],
  '458313': ['Emma Darricau',
   'Emma darricau',
   'Elisa-Specogna,  emma darricau',
   'Emma darricau-Delhay- Pelanne'],
  '458324': ['Elisa Lavielle'],
  '458329': ['hortense-delacou', 'hortense'],
  '458356': ['Victoria-Delhay Lucia-Pelanne',
   'victoria-delhay',
   'Victoria-delhay',
   'Emma darricau-Delhay- Pelanne',
   'Victoria-delhay Lucia-Pelanne'],
  '458391': [u'Ala\xefa / Le\xefla', u'Ala\xefa RD / Le\xefla Facon'],
  '458551': [u'Ala\xefa Robin Deguil',
   u'Ala\xefa',
   u'Ala\xefa / Le\xefla',
   u'Ala\xefa RD / Le\xefla Facon'],
  '458609': ['Roxane,Nina',
   u'roxane Sa\xefs, Nina callede',
   'Nina callede , roxane Sais',
   'Roxane sais, nina callede',
   u'Nina callede, roxane Sa\xefs'],
  '458613': [u'chlo\xe9-artola'],
  '458657': ['Oceane-defreitas'],
  '458667': [u'\xe9lisa-coureau. manon-rhode', 'Rhode-Manon', 'Manon-RHODE'],
  '458727': ['Lina-Bourchachene'],
  '458747': ['Elisa Specogna',
   'Elisa-Specogna,  emma darricau',
   'elisa-specogna',
   'Elisa-Specogna'],
  '458790': [u'Andr\xe9a'],
  '459136': ['EleonorecourtotMathildemajerus',
   'Eleonore/mathildemajerus',
   'Eleonore Courtot'],
  '459406': [u'\xe9lisa-coureau. manon-rhode',
   u'\xe9lisa_coureau',
   u'\xe9lisa-coureau'],
  '459660': [u'B\xe9a', 'Prep-prep'],
  '459692': [u'Ad\xe9lie Almon-Juliette Camut',
   u'Yuna-Gicquel. Ad\xe9lie.Almon',
   u'Ad\xe9lie-Almon Juliette-Camut',
   u'Yuna-Gicquel.Ad\xe9lie-Almon',
   u'Ad\xe9lie-Almon',
   u'Ad\xe9lie Qlmon',
   'Yuna-Gicquel. Adelie-almon'],
  '459959': ['justine-loustaunau'],
  '459971': [u'J\xe9r\xe9mie Dubois', u'J\xe9r\xe9mie-Dubois'],
  '460037': ['lana'],
  '460084': [u'Copp\xe9lia-SEYDI', u'Copp\xe9lia SEYDI', u'Copp\xe9lia seydi'],
  '460169': ['mintou_ndiaye'],
  '460344': ['Albanne Pagnoux-Pellegrino',
   'Pagnoux Albanne',
   'Pagnoux-Pellegrino-Albanne'],
  '460392': ['Sannah MAURINIER'],
  '460488': [u'Ad\xe8le.Stidler', u'Ad\xe8le-stidler'],
  '460525': ['Nassim Zahi'],
  '460583': [u'Madi'],
  '460829': ['lena-erc'],
  '460874': ['jeane gabaston'],
  '461104': ['Julia-Anoge-Elsa-Dumas'],
  '461111': [u'Mira'],
  '461325': ['Julia-Anoge-Elsa-Dumas'],
  '461847': ['Kameron rouyat'],
  '461900': ['sarah guellil', 'sarah-guellil'],
  '462309': ['Mame-Diop'],
  '462574': ['Simone_PRISCA_VAVY',
   u'simone_prisca_vavy',
   'Simone_prisca_vavy'],
  '463519': ['Nicolo Farris - Giulia Nisini'],
  '463523': ['ingrid fletcher'],
  '463562': ['Giulia Nisini', 'Nicolo Farris - Giulia Nisini'],
  '463682': ['Elisa-Fougere']}}

In [25]:
with codecs.open(fAliasQDLE, 'w', encoding="utf8") as outfile:
    yaml.safe_dump(correspondances, outfile, default_flow_style=False)

# Bonnes réponses pour les différents quizz du QuizzAll
- sur la deuxième ligne lQuizz[1], il y a toutes les bonnes réponses
- on coupe le Quizz All par groupe de trois questions pour chaque quizz d'origine
 - *quizzReponses*

In [26]:
with codecs.open(fQuizzoodle,"r",encoding="utf8") as input:
    lQuizz=input.readlines()

In [27]:
def chunks(l, n):
    """Yield successive n-sized chunks from l."""
    for i in range(0, len(l), n):
        yield l[i:i + n]

In [28]:
def getReponses(ligne):
    result={}
    ligneEls=[l.strip() for l in ligne.split(";")]
    pseudo=ligneEls[0]
    reponses=ligneEls[1:]
    for num,rep in enumerate(chunks(reponses,3)):
        result["%02d"%(num+2)]=rep
    return pseudo,result

In [29]:
temp,quizzReponses=getReponses(lQuizz[1])
quizzReponses

{'02': [u'E', u'F', u'G'],
 '03': [u'B', u'A', u'D'],
 '04': [u'B', u'A', u'A'],
 '05': [u'B', u'C', u'D'],
 '06': [u'D', u'D', u'C'],
 '07': [u'B', u'A', u'C'],
 '08': [u'C', u'A', u'D'],
 '09': [u'B', u'A', u'D'],
 '10': [u'B', u'C', u'D'],
 '11': [u'D', u'B', u'A']}

In [30]:
def markReponses(reponses):
    scores={}
    for q in quizzReponses:
#         print q
        score=0
        for n,r in enumerate(quizzReponses[q]):
#             print n,r,reponses[q][n]
            if r==reponses[q][n]:
                score+=1
        scores[q]=int(round(float(score)*20/3,0))    
    return scores

# Notes du pseudo pour les différents quizz
- sur la ligne du pseudo, on a toutes les réponses
- on coupe les réponses par groupe de trois réponses
- on compare avec les bonnes réponses

In [31]:
alias[u"mon-a sal-a"]

KeyError: u'mon-a sal-a'

In [32]:
quizzNotes={}
for l in lQuizz[2:]:
    nom,reponses=getReponses(l)
#     print nom,reponses
    
    marks=markReponses(reponses)
    
#     print nom, " ; ".join([str(marks[k]) for k in sorted(marks.keys())])
    
    if nom in alias:
#         print nom,alias[nom]
        akas=alias[nom]
    else:
        print "pas de",nom
        akas=[]
        
    for aka in akas:
        if aka in quizzNotes:
            print aka,"déjà dans les notes",invAlias[aka]
            print quizzNotes[aka]
            print marks
            for k,v in quizzNotes[aka].iteritems():
                if v<marks[k]:
                    quizzNotes[aka][k]=marks[k]
            print quizzNotes[aka]
        else:
            quizzNotes[aka]=marks
print 
print "===================="
print
for aka in sorted(quizzNotes.keys()):
#    print chercherIdentifiant(aka)
    print aka, ", ".join([str(quizzNotes[aka][k]) for k in sorted(quizzNotes[aka].keys())])

====================

396581 7, 7, 13, 7, 7, 7, 13, 0, 7, 7
414295 20, 20, 7, 20, 7, 7, 0, 7, 7, 13
430746 0, 0, 0, 13, 0, 0, 7, 13, 13, 7
441018 13, 7, 7, 13, 13, 7, 7, 7, 7, 0
446384 0, 0, 0, 13, 0, 7, 13, 13, 13, 7
450931 13, 0, 13, 13, 0, 13, 13, 7, 20, 7
452779 7, 7, 13, 7, 13, 20, 7, 13, 7, 0
453815 7, 7, 7, 7, 7, 7, 7, 7, 7, 7
454079 20, 13, 7, 13, 7, 0, 7, 13, 7, 7
454852 0, 7, 0, 13, 13, 13, 7, 7, 0, 13
455719 0, 13, 0, 20, 13, 13, 7, 7, 7, 0
456651 13, 7, 13, 7, 13, 0, 7, 7, 20, 0
456672 13, 7, 7, 7, 20, 7, 13, 20, 7, 7
456690 13, 13, 13, 13, 7, 0, 7, 7, 13, 13
456846 20, 0, 7, 13, 0, 7, 13, 7, 7, 7
457111 7, 13, 13, 13, 0, 7, 0, 7, 13, 13
457483 13, 7, 7, 13, 0, 7, 7, 0, 0, 0
457714 13, 13, 7, 13, 7, 13, 7, 0, 0, 13
457731 13, 0, 7, 0, 13, 13, 7, 13, 7, 7
457952 0, 0, 7, 13, 0, 0, 7, 13, 13, 7
457961 0, 7, 7, 0, 7, 7, 7, 0, 7, 0
458113 0, 0, 7, 13, 7, 7, 7, 13, 7, 13
458551 13, 7, 7, 7, 7, 7, 0, 0, 0, 0
458613 0, 13, 13, 20, 7, 7, 0, 20, 13, 0
458657 20, 7, 0, 7, 13, 7, 13, 20, 7, 7
458747 13, 7, 0, 13, 13, 7, 13, 13, 7, 0
459692 20, 0, 7, 13, 0, 13, 7, 0, 13, 7
459971 7, 13, 13, 7, 7, 0, 13, 0, 13, 0
460084 7, 0, 20, 20, 7, 7, 13, 13, 13, 13
460488 13, 7, 13, 7, 13, 0, 7, 20, 7, 7
460583 0, 7, 13, 7, 0, 7, 7, 0, 0, 7
461111 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
462574 13, 7, 7, 13, 7, 7, 7, 7, 7, 13

In [33]:
quizzNotes[u"443367"]

KeyError: u'443367'

In [35]:
dfNotesOriginales=pd.read_excel(fNotesOriginales)
dfNotesOriginales[u"Numéro d’identification"]=dfNotesOriginales[u"Numéro d’identification"].astype("int").astype("str")
dfNotesOriginales[["Nom"]+["Q%02d"%i for i in range(2,12)]]

                    Nom Q02 Q03 Q04 Q05 Q06 Q07 Q08 Q09 Q10 Q11
0       ABDALLAH TOMANY   -   -   -   -   -   -   -   -   -   -
1            ABDELJALIL   -   -   -   -   -   -   -   -   -   -
2                 AGGAR   -   -   -   -   -   -   -   -   -   -
3             AGLETINER  19  16  13  17  14  10  17  15  15  13
4                 ALBON  19  14  11  19  18  16  20  13  15  12
5                 ALMON  16   -   -  16  14  13  13  18  17  13
6               ALTENOR   -   -   -   -   -   -   -   -   -   -
7                ANDRAC   -   -   -   -   -   -   -   -   -   -
8               ANDRADE  14  20  11  19  14  14  10  13  17  15
9                 ANOGE  14   -   -   -   -   -   -   -   -   -
10               ARTOLA  13  16  13  19  13  14  13  15  12  18
11      ATAM-KASSIGADOU   -   -   -   -   -   -   -   -   -   -
12              AUGUSTE  14  16  17  20  14  14  13  17  13  20
13               BARBRY   -   -   -   -   -   -  10  12   -   -
14                BARBU   -   -   -   -   -   -   -   -   -   -
15           BELFERKOUS   -   -   -   -   -   -   -   -   -   -
16            BENAOUDIA   -   8  13   8  11  13  13  12  10  10
17            BESSONART  16  14  11   -   -   -  18  13   -   -
18                BLANC   -   -   -   -   -   -   -   -   -   -
19            BLANCHARD  16   -   -   -   -   -   -   -   -   -
20           BONETBELTS  20  16  14  14   -  10  17  15   -  12
21                BOUIN   -   -   -   -   -   -   -   -   -   -
22         BOURCHACHENE  13   -   -   -   -   -   -   -   -   -
23              BOUREMA  13  14  14  17   -   -   -   -  12   -
24         CAID ESSEBSI   -   -   -   -   -   -   -   -   -   -
25              CALLEDE  17  14   -  16   -  13   -   -   -   -
26            CAMBARRAT   -   -   -   -   -   -   -   -   -   -
27                CAMUT  16  16  16  16  11  13  13  18  17  15
28                CANLI  17  13  18   -  14   -   -   -   -  13
29              CAPRAJA  16   -   -  16  11   -   -   -   -   -
..                  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
132             POINSOT   -   -   -   -   -   -   -   -   -   -
133  POULET--CONSTANTIN   -   -   -   -   -   -   -   -   -   -
134   POVEDA-DURASTANTI   -  13  13   -   -   -   -   -   -   -
135              PREVOT   -   -   -   -   -   -   -   -   -   -
136         PRISCA VAVY  16  14  17   -   -   -  12  17   -   -
137              QARTIT   -   -   -   -   -   -   -   -   -   -
138            RAFFALLI   -   -   -   -   -   -   -   -   -   -
139         RAHARIJAONA   -   -   -   -   -   -   -   -   -   -
140     RAOULT--DESTOUR   -   -   -   -   -   -   -   -   -   -
141             RECULET   -   -   -   -   -   -   -   -   -   -
142               RHODE  17  11   -  17  11  14  10   -  15   -
143               RIAUD  16  14  16  16  11  11  13  18  17  15
144             RICHAUD   -   -   -   -   -   -   -   -   -   -
145            RICHAUME   -   -   -   -   -   -   -   -   -   -
146             RIVIERE  14   -   -  19   -   -   -   -   -   -
147       ROBIN--DEGUIL  17  16  17  16   -   -   -   -   -  15
148              ROUYAT  19   -   -   -   -   -   -   -   -   -
149               SAIDI   -   -   -   -   -   -   -   -   -   -
150                SAIS  17  14   -  16   -  13   -   -   -   -
151               SAUZE   -   -   -   -   -   -   -   -   -   -
152               SEYDI  16  14  14  19  13  14  15  17  13  12
153            SIGISCAR   -   -   -   -   -   -   -   -   -   -
154             SOUCHET   -  14  11  17  20  14  13  15  20  12
155            SPECOGNA  14  13  13  19  14  16  15  18   -  10
156             STIDLER  16  13  14  16  10  10  15  13  15  13
157                TANG   -   -   -   -   -   -   -   -   -   -
158              TIXIER   -   -   -   -   -   -   -   -   -   -
159              VAGNER   -   -   -   -   -   -   -   -   -   -
160                ZAHI  16   -   -   -   -   -   -   -   -   -
161               ZAIRI   -   -   -   -   -   -   -   -   -   -

[162 rows x 11 columns]

In [36]:
# dfCampus=dfNotesOriginales[[u"Numéro d'identification"]+u"Nom Prénom".split(" ")+["Quizz%02d (Brut)"%(i+1) for i in range(1,10)]]
dfCampus=dfNotesOriginales[[u"Numéro d’identification"]+u"Nom Prénom".split(" ")+["Q%02d"%(i+1) for i in range(1,11)]]
dfCampus.set_index(u"Numéro d’identification",inplace=True)
# dfCampus.loc["417001"]

In [37]:
nouvellesNotes={}
for etu in quizzNotes:
    print etu
    if etu in dfCampus.index:
        for q in quizzNotes[etu]:
            # if quizzNotes[etu][q] > dfCampus.loc[etu,"Quizz%s (Brut)"%q] or dfCampus.loc[etu,"Quizz%s (Brut)"%q]=="-":
            if quizzNotes[etu][q] > dfCampus.loc[etu,"Q%s"%q] or dfCampus.loc[etu,"Q%s"%q]=="-" or dfCampus.loc[etu,"Q%s"%q]!=dfCampus.loc[etu,"Q%s"%q]:
                # print u"Quizz %s"%q,dfCampus.loc[etu,"Quizz%s (Brut)"%q],"=>",quizzNotes[etu][q]
                print u"Quizz %s"%q,dfCampus.loc[etu,"Q%s"%q],"=>",quizzNotes[etu][q]
                if not etu in nouvellesNotes:
                    nouvellesNotes[etu]={}
                nouvellesNotes[etu][q]=quizzNotes[etu][q]
                # dfCampus.loc[etu,"Quizz%s (Brut)"%q]=quizzNotes[etu][q]
                dfCampus.loc[etu,"Q%s"%q]=quizzNotes[etu][q]
    else:
        print "PB", etu, "pas de notes originales"
        print quizzNotes[etu]
        nouvellesNotes[etu]=quizzNotes[etu]
len(nouvellesNotes)

453815
459692
Quizz 02 16 => 20
Quizz 03 - => 0
Quizz 04 - => 7
460084
Quizz 04 14 => 20
Quizz 05 19 => 20
Quizz 11 12 => 13
461111

/opt/anaconda3/envs/python2/lib/python2.7/site-packages/pandas/core/indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
/opt/anaconda3/envs/python2/lib/python2.7/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

Quizz 02 - => 0
Quizz 03 - => 0
Quizz 06 - => 0
Quizz 07 - => 0
Quizz 04 - => 0
Quizz 05 - => 0
Quizz 08 - => 0
Quizz 09 - => 0
Quizz 11 - => 0
Quizz 10 - => 0
457961
Quizz 03 - => 7
Quizz 10 - => 7
454079
Quizz 02 16 => 20
Quizz 07 - => 0
Quizz 05 - => 13
Quizz 11 - => 7
396581
Quizz 04 11 => 13
458747
Quizz 10 - => 7
456651
Quizz 10 13 => 20
452779
Quizz 03 - => 7
Quizz 06 10 => 13
Quizz 07 14 => 20
Quizz 04 - => 13
456690
Quizz 03 11 => 13
Quizz 10 - => 13
458657
Quizz 02 14 => 20
Quizz 05 - => 7
Quizz 09 15 => 20
Quizz 11 - => 7
454852
Quizz 03 - => 7
Quizz 04 - => 0
446384
430746
Quizz 02 - => 0
Quizz 05 - => 13
457483
Quizz 10 - => 0
458551
Quizz 06 - => 7
Quizz 07 - => 7
Quizz 08 - => 0
Quizz 09 - => 0
Quizz 10 - => 0
456672
Quizz 03 - => 7
Quizz 06 - => 20
Quizz 07 - => 7
Quizz 04 - => 7
Quizz 05 - => 7
Quizz 09 13 => 20
Quizz 11 - => 7
462574
Quizz 06 - => 7
Quizz 07 - => 7
Quizz 05 - => 13
Quizz 11 - => 13
Quizz 10 - => 7
450931
Quizz 07 11 => 13
Quizz 10 17 => 20
456846
Quizz 02 16 => 20
455719
Quizz 03 - => 13
Quizz 06 - => 13
Quizz 04 - => 0
Quizz 05 17 => 20
Quizz 10 - => 7
457952
460488
Quizz 06 10 => 13
Quizz 09 13 => 20
460583
Quizz 02 - => 0
Quizz 03 - => 7
Quizz 06 - => 0
Quizz 07 - => 7
Quizz 04 - => 13
Quizz 05 - => 7
Quizz 08 - => 7
Quizz 09 - => 0
Quizz 11 - => 7
Quizz 10 - => 0
414295
Quizz 02 14 => 20
Quizz 05 19 => 20
457111
Quizz 10 12 => 13
458613
Quizz 05 19 => 20
Quizz 09 15 => 20
Quizz 10 12 => 13
457731
Quizz 05 - => 0
457714
Quizz 02 - => 13
Quizz 07 - => 13
Quizz 11 - => 13
441018
Quizz 03 - => 7
Quizz 06 - => 13
Quizz 07 - => 7
Quizz 04 - => 7
Quizz 08 - => 7
Quizz 09 - => 7
Quizz 11 - => 0
Quizz 10 - => 7
459971
458113

28

In [38]:
dfCampus

,Nom,Prénom,Q02,Q03,Q04,Q05,Q06,Q07,Q08,Q09,Q10,Q11
Numéro d’identification,,,,,,,,,,,,
455717,ABDALLAH TOMANY,SHAIMA,-,-,-,-,-,-,-,-,-,-
429665,ABDELJALIL,LINA,-,-,-,-,-,-,-,-,-,-
461076,AGGAR,LYDIA,-,-,-,-,-,-,-,-,-,-
458113,AGLETINER,NELIA,19,16,13,17,14,10,17,15,15,13
396581,ALBON,LWANN,19,14,13,19,18,16,20,13,15,12
459692,ALMON,ADELIE,20,0,7,16,14,13,13,18,17,13
446215,ALTENOR,SERIANE,-,-,-,-,-,-,-,-,-,-
435583,ANDRAC,NELL,-,-,-,-,-,-,-,-,-,-
414295,ANDRADE,TIMOTHY,20,20,11,20,14,14,10,13,17,15
461104,ANOGE,JULIA,14,-,-,-,-,-,-,-,-,-
458613,ARTOLA,CHLOE,13,16,13,20,13,14,13,20,13,18
441237,ATAM-KASSIGADOU,ELIZA,-,-,-,-,-,-,-,-,-,-
456651,AUGUSTE,MAELA,14,16,17,20,14,14,13,17,20,20
457795,BARBRY,LILY,-,-,-,-,-,-,10,12,-,-
445372,BARBU,MATEI-TEODOR,-,-,-,-,-,-,-,-,-,-
460351,BELFERKOUS,MAISSA,-,-,-,-,-,-,-,-,-,-
434036,BENAOUDIA,AHCENE,-,8,13,8,11,13,13,12,10,10
457173,BESSONART,MATHILDE,16,14,11,-,-,-,18,13,-,-
460714,BLANC,LAURINE,-,-,-,-,-,-,-,-,-,-
458790,BLANCHARD,ANDREA,16,-,-,-,-,-,-,-,-,-
454875,BONETBELTS,ANAIS,20,16,14,14,-,10,17,15,-,12
460512,BOUIN,VALENTINE,-,-,-,-,-,-,-,-,-,-
458727,BOURCHACHENE,LINA,13,-,-,-,-,-,-,-,-,-
416701,BOUREMA,OMEIMA,13,14,14,17,-,-,-,-,12,-
450856,CAID ESSEBSI,NOUR,-,-,-,-,-,-,-,-,-,-
458609,CALLEDE,NINA,17,14,-,16,-,13,-,-,-,-
459964,CAMBARRAT,MARGAUX,-,-,-,-,-,-,-,-,-,-
446384,CAMUT,JULIETTE,16,16,16,16,11,13,13,18,17,15
456710,CANLI,SEMA,17,13,18,-,14,-,-,-,-,13
457965,CAPRAJA,LILA,16,-,-,16,11,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...
460309,POINSOT,KATHLEEN,-,-,-,-,-,-,-,-,-,-
459745,POULET--CONSTANTIN,ANNA,-,-,-,-,-,-,-,-,-,-
454341,POVEDA-DURASTANTI,MAELLE,-,13,13,-,-,-,-,-,-,-
458341,PREVOT,EMMA,-,-,-,-,-,-,-,-,-,-
462574,PRISCA VAVY,SIMONE,16,14,17,13,7,7,12,17,7,13
458209,QARTIT,SHAIMA,-,-,-,-,-,-,-,-,-,-
457340,RAFFALLI,MARIE-DIANE,-,-,-,-,-,-,-,-,-,-
461334,RAHARIJAONA,MIARANA HAMY FITAHIA,-,-,-,-,-,-,-,-,-,-
460054,RAOULT--DESTOUR,ARTEMIS,-,-,-,-,-,-,-,-,-,-
426755,RECULET,MARIUS,-,-,-,-,-,-,-,-,-,-
458667,RHODE,MANON,17,11,-,17,11,14,10,-,15,-
450931,RIAUD,MELISSANDRE,16,14,16,16,11,13,13,18,20,15
458319,RICHAUD,CHLOE,-,-,-,-,-,-,-,-,-,-
461303,RICHAUME,JULIEN,-,-,-,-,-,-,-,-,-,-
441018,RIVIERE,LUCIE,14,7,7,19,13,7,7,7,7,0
458551,ROBIN--DEGUIL,ALAIA,17,16,17,16,7,7,0,0,0,15
461847,ROUYAT,KAMERON,19,-,-,-,-,-,-,-,-,-
454123,SAIDI,NOUHAILA,-,-,-,-,-,-,-,-,-,-
455153,SAIS,ROXANE,17,14,-,16,-,13,-,-,-,-
382568,SAUZE,THOMAS,-,-,-,-,-,-,-,-,-,-
460084,SEYDI,COPPELIA,16,14,20,20,13,14,15,17,13,13
446347,SIGISCAR,CANDYCE,-,-,-,-,-,-,-,-,-,-
459660,SOUCHET,BEATRICE,-,14,11,17,20,14,13,15,20,12
458747,SPECOGNA,ELISA,14,13,13,19,14,16,15,18,7,10
460488,STIDLER,ADELE,16,13,14,16,13,10,15,20,15,13
457363,TANG,YING CHEUNG,-,-,-,-,-,-,-,-,-,-
459756,TIXIER,AMELYNE,-,-,-,-,-,-,-,-,-,-
453907,VAGNER,CORALIE,-,-,-,-,-,-,-,-,-,-
460525,ZAHI,NASSIM,16,-,-,-,-,-,-,-,-,-
460114,ZAIRI,NAOMIE,-,-,-,-,-,-,-,-,-,-

In [39]:
numId="449233"
dfCampus.loc[numId],dfNotesOriginales[dfNotesOriginales[u"Numéro d’identification"]==numId]

KeyError: u'the label [449233] is not in the [index]'

In [40]:
dfCampus.to_excel(fNotesFinales)