In [1]:
import codecs,unidecode,yaml,glob,os,shutil,re
import itertools as it
import numpy as np
import pandas as pd
# print(pd.__version__)

In [153]:
sQuizz="11"
nQuizz=int(sQuizz)
fCM=u"/Users/gilles/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/01-NotesQuizz/CM.csv"
fAliasQDLE=u"/Users/gilles/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/01-NotesQuizz/Quizz-Alias.yaml"
fQuizzoodle=u"/Users/gilles/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/01-NotesQuizz/Quizz-%s.csv"%sQuizz
# fQuizzoodle=u"/Users/gilles/ownCloud/Cours/Bordeaux/L1-UE4-Morphologie/24-Quizz/Quizz-%s.csv"%sQuizz
fNotes=fQuizzoodle.replace(u".csv",u"-Notes.csv")
print fCM,fQuizzoodle

/Users/gilles/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/01-NotesQuizz/CM.csv /Users/gilles/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/01-NotesQuizz/Quizz-11.csv

In [154]:
'''https://stackoverflow.com/a/35491326/3986209'''
def invert_dict(d): 
    inverse = dict() 
    for key in d: 
        # Go through the list that is saved in the dict:
        for item in d[key]:
            # Check if in the inverted dict the key exists
            if item not in inverse: 
                # If not create a new list
                inverse[item] = [key] 
            else: 
                inverse[item].append(key) 
    return inverse

# Lecture des données

In [155]:
try:
    with codecs.open(fAliasQDLE, 'r', encoding="utf8") as inFile:
        correspondances=yaml.safe_load(inFile)
    alias=correspondances["alias2etu"]
except:
    alias={}
# alias

In [156]:
len(alias)

139

In [157]:
colCM=[u"id",u"nom",u"prénom",u"email",u"ine"]
colQuizz=["pseudo","points","temps"]

try:
    dfCM=pd.read_csv(fCM,sep="\t",encoding="utf8",header=0,names=colCM)
    lQuizz=pd.read_csv(fQuizzoodle,sep=";",encoding="utf8",header=0,names=colQuizz)
    lQuizz.pseudo=lQuizz.pseudo.str.strip()
except:
    dfCM=None
    lQuizz=None

In [158]:
lQuizz, dfCM

(                           pseudo  points   temps
 0                   maela.auguste       5  231.72
 1                    chloé-artola       4   95.76
 2                   manon-olivier       4  183.72
 3                     anais-manus       4  194.88
 4                  Juliette-camut       3   89.69
 5               Mélissandre-Riaud       3  140.87
 6                   Dupouy-Leonie       3  141.59
 7                    Yuna-Gicquel       3  170.55
 8                           Alaïa       3  192.26
 9                    Lubin Joakim       3  214.01
 10                  Elisa Lucante       3  228.85
 11                timothy-andrade       3  251.98
 12                Chloé- Cartigny       2   45.86
 13                   Adélie-Almon       2   88.27
 14                  Adèle.Stidler       2  164.30
 15                nélia-agletiner       2  172.07
 16                           Sema       2  172.83
 17  Victoria-Delhay Lucia-Pelanne       2  180.16
 18               Mélanie Lassagne       2  185.01
 19                  Emma darricau       2  207.49
 20               hortense-delacou       2  238.89
 21               anais.bonetbelts       1  101.24
 22                    albon lwann       1  119.11
 23                      Prep-prep       1  140.77
 24                 Coppélia-SEYDI       1  149.45
 25          Maena Lamolere—Phelep       1  152.01
 26                  louise.laveau       1  178.67
 27      Charlotte-mariagecornille       1  200.10
 28                 Jérémie Dubois       1  225.36
 29                milena-hamilton       1  245.90
 30                        Mélanie       0    0.00
 31                         Ahcene       0   83.55
 32                 Elisa Specogna       0   93.55
 33                 Louhane.crowin       0  140.00
 34               melissa-johannet       0  186.60,
          id                 nom                prénom  \
 0    455717     ABDALLAH TOMANY                SHAIMA
 1    429665          ABDELJALIL                  LINA
 2    461076               AGGAR                 LYDIA
 3    458113           AGLETINER                 NELIA
 4    396581               ALBON                 LWANN
 5    459692               ALMON                ADELIE
 6    446215             ALTENOR               SERIANE
 7    435583    ANDRAC-PEPERMANS                  NELL
 8    414295             ANDRADE               TIMOTHY
 9    461104               ANOGE                 JULIA
 10   458613              ARTOLA                 CHLOE
 11   441237     ATAM-KASSIGADOU                 ELIZA
 12   456651             AUGUSTE                 MAELA
 13   457795              BARBRY                  LILY
 14   445372               BARBU          MATEI-TEODOR
 15   460351          BELFERKOUS                MAISSA
 16   434036           BENAOUDIA                AHCENE
 17   457173           BESSONART              MATHILDE
 18   460714               BLANC               LAURINE
 19   458790           BLANCHARD                ANDREA
 20   454875          BONETBELTS                 ANAIS
 21   460512               BOUIN             VALENTINE
 22   458727        BOURCHACHENE                  LINA
 23   416701             BOUREMA                OMEIMA
 24   450856        CAID ESSEBSI                  NOUR
 25   458609             CALLEDE                  NINA
 26   459964           CAMBARRAT               MARGAUX
 27   446384               CAMUT              JULIETTE
 28   456710               CANLI                  SEMA
 29   457965             CAPRAJA                  LILA
 ..      ...                 ...                   ...
 132  460309             POINSOT              KATHLEEN
 133  459745  POULET--CONSTANTIN                  ANNA
 134  454341   POVEDA-DURASTANTI                MAELLE
 135  458341              PREVOT                  EMMA
 136  462574         PRISCA VAVY                SIMONE
 137  458209              QARTIT                SHAIMA
 138  457340            RAFFALLI           MARIE-DIANE
 139  461334         RAHARIJAONA  MIARANA HAMY FITAHIA
 140  460054     RAOULT--DESTOUR               ARTEMIS
 141  426755             RECULET                MARIUS
 142  458667               RHODE                 MANON
 143  450931               RIAUD           MELISSANDRE
 144  458319             RICHAUD                 CHLOE
 145  461303            RICHAUME                JULIEN
 146  441018             RIVIERE                 LUCIE
 147  458551       ROBIN--DEGUIL                 ALAIA
 148  461847              ROUYAT               KAMERON
 149  454123               SAIDI              NOUHAILA
 150  455153                SAIS                ROXANE
 151  382568               SAUZE                THOMAS
 152  460084               SEYDI              COPPELIA
 153  446347            SIGISCAR               CANDYCE
 154  459660             SOUCHET              BEATRICE
 155  458747            SPECOGNA                 ELISA
 156  460488             STIDLER                 ADELE
 157  457363                TANG           YING CHEUNG
 158  459756              TIXIER               AMELYNE
 159  453907              VAGNER               CORALIE
 160  460525                ZAHI                NASSIM
 161  460114               ZAIRI                NAOMIE

                                                  email         ine
 0    shaima.abdallah-tomany@etu.u-bordeaux-montaign...  1772291711
 1          lina.abdeljalil@etu.u-bordeaux-montaigne.fr  1772291711
 2              lydia.aggar@etu.u-bordeaux-montaigne.fr  1772291711
 3          nelia.agletiner@etu.u-bordeaux-montaigne.fr  1772291711
 4              lwann.albon@etu.u-bordeaux-montaigne.fr  1772291711
 5             adelie.almon@etu.u-bordeaux-montaigne.fr  1772291711
 6          seriane.altenor@etu.u-bordeaux-montaigne.fr  1772291711
 7    nell.andrac-pepermans@etu.u-bordeaux-montaigne.fr  1772291711
 8          timothy.andrade@etu.u-bordeaux-montaigne.fr  1772291711
 9              julia.anoge@etu.u-bordeaux-montaigne.fr  1772291711
 10            chloe.artola@etu.u-bordeaux-montaigne.fr  1772291711
 11   eliza.atam-kassigadou@etu.u-bordeaux-montaigne.fr  1772291711
 12           maela.auguste@etu.u-bordeaux-montaigne.fr  1772291711
 13             lily.barbry@etu.u-bordeaux-montaigne.fr  1772291711
 14      matei-teodor.barbu@etu.u-bordeaux-montaigne.fr  1772291711
 15       maissa.belferkous@etu.u-bordeaux-montaigne.fr  1772291711
 16        ahcene.benaoudia@etu.u-bordeaux-montaigne.fr  1772291711
 17      mathilde.bessonart@etu.u-bordeaux-montaigne.fr  1772291711
 18           laurine.blanc@etu.u-bordeaux-montaigne.fr  1772291711
 19        andrea.blanchard@etu.u-bordeaux-montaigne.fr  1772291711
 20        anais.bonetbelts@etu.u-bordeaux-montaigne.fr  1772291711
 21         valentine.bouin@etu.u-bordeaux-montaigne.fr  1772291711
 22       lina.bourchachene@etu.u-bordeaux-montaigne.fr  1772291711
 23          omeima.bourema@etu.u-bordeaux-montaigne.fr  1772291711
 24       nour.caid-essebsi@etu.u-bordeaux-montaigne.fr  1772291711
 25            nina.callede@etu.u-bordeaux-montaigne.fr  1772291711
 26       margaux.cambarrat@etu.u-bordeaux-montaigne.fr  1772291711
 27          juliette.camut@etu.u-bordeaux-montaigne.fr  1772291711
 28              sema.canli@etu.u-bordeaux-montaigne.fr  1772291711
 29            lila.capraja@etu.u-bordeaux-montaigne.fr  1772291711
 ..                                                 ...         ...
 132       kathleen.poinsot@etu.u-bordeaux-montaigne.fr  1772291711
 133  anna.poulet--constantin@etu.u-bordeaux-montaig...  1772291711
 134  maelle.poveda-durastanti@etu.u-bordeaux-montai...  1772291711
 135            emma.prevot@etu.u-bordeaux-montaigne.fr  1772291711
 136     simone.prisca-vavy@etu.u-bordeaux-montaigne.fr  1772291711
 137          shaima.qartit@etu.u-bordeaux-montaigne.fr  1772291711
 138   marie-diane.raffalli@etu.u-bordeaux-montaigne.fr  1772291711
 139  miarana-hamy-fitahia.raharijaona@etu.u-bordeau...  1772291711
 140  artemis.raoult--destour@etu.u-bordeaux-montaig...  1772291711
 141         marius.reculet@etu.u-bordeaux-montaigne.fr  1772291711
 142            manon.rhode@etu.u-bordeaux-montaigne.fr  1772291711
 143      melissandre.riaud@etu.u-bordeaux-montaigne.fr  1772291711
 144          chloe.richaud@etu.u-bordeaux-montaigne.fr  1772291711
 145        julien.richaume@etu.u-bordeaux-montaigne.fr  1772291711
 146         lucie.riviere1@etu.u-bordeaux-montaigne.fr  1772291711
 147    alaia.robin--deguil@etu.u-bordeaux-montaigne.fr  1772291711
 148         kameron.rouyat@etu.u-bordeaux-montaigne.fr  1772291711
 149         nouhaila.saidi@etu.u-bordeaux-montaigne.fr  1772291711
 150            roxane.sais@etu.u-bordeaux-montaigne.fr  1772291711
 151           thomas.sauze@etu.u-bordeaux-montaigne.fr  1772291711
 152         coppelia.seydi@etu.u-bordeaux-montaigne.fr  1772291711
 153       candyce.sigiscar@etu.u-bordeaux-montaigne.fr  1772291711
 154       beatrice.souchet@etu.u-bordeaux-montaigne.fr  1772291711
 155         elisa.specogna@etu.u-bordeaux-montaigne.fr  1772291711
 156          adele.stidler@etu.u-bordeaux-montaigne.fr  1772291711
 157       ying-cheung.tang@etu.u-bordeaux-montaigne.fr  1772291711
 158         amelyne.tixier@etu.u-bordeaux-montaigne.fr  1772291711
 159         coralie.vagner@etu.u-bordeaux-montaigne.fr  1772291711
 160            nassim.zahi@etu.u-bordeaux-montaigne.fr  1772291711
 161           naomie.zairi@etu.u-bordeaux-montaigne.fr  1772291711

 [162 rows x 5 columns])

In [159]:
pseudos=lQuizz[~(lQuizz["pseudo"].isin(alias))]["pseudo"].str.strip().tolist()
print "\n".join(pseudos)

Adélie-Almon
Sema
Mélanie
Louhane.crowin

# Listage des alias

In [160]:
dfCM["PN"]=dfCM[u"prénom"].str.lower().str.strip()+" "+dfCM[u"nom"].str.lower().str.strip()
dfCM["NP"]=dfCM[u"nom"].str.lower().str.strip()+" "+dfCM[u"prénom"].str.lower().str.strip()
dfCM["P-N"]=dfCM[u"prénom"].str.lower().str.strip()+"-"+dfCM[u"nom"].str.lower().str.strip()
dfCM["N-P"]=dfCM[u"nom"].str.lower().str.strip()+"-"+dfCM[u"prénom"].str.lower().str.strip()
dfCM["P.N"]=dfCM[u"prénom"].str.lower().str.strip()+"."+dfCM[u"nom"].str.lower().str.strip()
dfCM["N.P"]=dfCM[u"nom"].str.lower().str.strip()+"."+dfCM[u"prénom"].str.lower().str.strip()
# dfCM

pn=dfCM["PN"].tolist()
p_n=dfCM["P-N"].tolist()
np=dfCM["NP"].tolist()
n_p=dfCM["N-P"].tolist()

In [161]:
pn=dfCM["PN"].tolist()
pnT=dfCM["P-N"].tolist()
pnD=dfCM["P.N"].tolist()
np=dfCM["NP"].tolist()
npT=dfCM["N-P"].tolist()
npD=dfCM["N.P"].tolist()
lNomPrenom={"PN":pn,"P-N":pnT,"P.N":pnD,"NP":np,"N-P":npT,"N.P":npD}

In [162]:
for pseudo in pseudos:
    for nomPrenom in lNomPrenom:
        if unidecode.unidecode(pseudo.lower()) in lNomPrenom[nomPrenom]:
            print pseudo,dfCM[dfCM[nomPrenom]==unidecode.unidecode(pseudo.lower())]["id"].values[0]
            alias[pseudo]=[str(dfCM[dfCM[nomPrenom]==unidecode.unidecode(pseudo.lower())]["id"].values[0])]

Adélie-Almon 459692
Louhane.crowin 453815

In [163]:
pseudos=lQuizz[~(lQuizz["pseudo"].isin(alias))]["pseudo"].str.strip().tolist()
print "\n".join(pseudos)

Sema
Mélanie

In [164]:
for nP,pseudoBrut in enumerate(pseudos):
    pseudo=unidecode.unidecode(pseudoBrut)
    print pseudo
    sPseudo = raw_input("Nom a chercher:\n")
    if sPseudo:
        print dfCM[dfCM["PN"].str.contains(sPseudo.lower())][["PN","id"]]
        idPseudo=raw_input("id :\n")
        if idPseudo:
            alias[pseudoBrut]=idPseudo

Sema

Nom a chercher:
 Sema

            PN      id
28  sema canli  456710

id :
 456710

Melanie

Nom a chercher:
 430746

Empty DataFrame
Columns: [PN, id]
Index: []

id :

for k,v in alias.iteritems():
    print k,v[0][0][0]
    alias[k]=v[0][0][0].split(" ")
alias

In [165]:
# pseudo=u"csaintavi001 ebismes001"
# alias[pseudo]=["415962","413429"]

In [166]:
sPseudo="bisme"
print dfCM[dfCM["PN"].str.contains(sPseudo.lower())][["PN","id"]]

Empty DataFrame
Columns: [PN, id]
Index: []

In [167]:
pseudos

[u'Sema', u'M\xe9lanie']

In [168]:
# alias["Sofiane"]

In [169]:
for al in alias:
    if not isinstance(alias[al],list):
        if " " in alias[al]:
            alias[al]=alias[al].split(" ")
        else:
            alias[al]=[alias[al]]

In [170]:
len(alias)

142

In [171]:
invAlias=invert_dict(alias)
#invAlias[385732]=[u'adiarra001, cbeauvais004']
correspondances={"alias2etu":alias,"etu2alias":invAlias}
correspondances

{'alias2etu': {u'Ad\xe8le-stidler': ['460488'],
  u'Ad\xe8le.Stidler': ['460488'],
  u'Ad\xe9lie Almon-Juliette Camut': ['459692', '446384'],
  u'Ad\xe9lie Qlmon': ['459692'],
  u'Ad\xe9lie-Almon': ['459692'],
  u'Ad\xe9lie-Almon Juliette-Camut': ['459692', '446384'],
  'Ahcene': ['434036'],
  u'Ala\xefa': ['458551'],
  u'Ala\xefa / Le\xefla': ['458551', '458391'],
  u'Ala\xefa RD / Le\xefla Facon': ['458551', '458391'],
  u'Ala\xefa Robin Deguil': ['458551'],
  'Albanne Pagnoux-Pellegrino': ['460344'],
  'Anais-manus': ['457731'],
  u'Ana\xebl': ['453951'],
  u'Andr\xe9a': ['458790'],
  u'B\xe9a': ['459660'],
  'Charlotte-mariagecornille': ['453211'],
  u'Chlo\xe9- Cartigny': ['453789'],
  u'Copp\xe9lia SEYDI': ['460084'],
  u'Copp\xe9lia seydi': ['460084'],
  u'Copp\xe9lia-SEYDI': ['460084'],
  'Dupouy-Leonie': ['456690'],
  'Eleonore Courtot': ['459136'],
  'Eleonore/mathildemajerus': ['459136', '458207'],
  'EleonorecourtotMathildemajerus': ['459136', '458207'],
  'Elisa Lavielle': ['458324'],
  'Elisa Lucante': ['457483'],
  'Elisa Specogna': ['458747'],
  'Elisa-Fougere': ['463682'],
  'Elisa-Specogna': ['458747'],
  'Elisa-Specogna,  emma darricau': ['458747', '458313'],
  'Emma Darricau': ['458313'],
  'Emma darricau': ['458313'],
  'Emma darricau-Delhay- Pelanne': ['458313', '458356', '458010'],
  'Fevre Faustine': ['456672'],
  'GUETATFA Ilhem': ['447671'],
  'Giulia Nisini': ['463562'],
  'Joakim-Lubin': ['457111'],
  'Julia-Anoge-Elsa-Dumas': ['461104', '461325'],
  'Juliette-camut': ['446384'],
  'Juliette-camut Lila-Capraja': ['446384', '457965'],
  u'Juliette-camut M\xe9li-riaud': ['446384', '450931'],
  u'J\xe9r\xe9mie Dubois': ['459971'],
  u'J\xe9r\xe9mie-Dubois': ['459971'],
  'Kameron rouyat': ['461847'],
  'Leonie Dupuy': ['456690'],
  'Lila-Capraja': ['457965'],
  'Lina-Bourchachene': ['458727'],
  u'Louhane.crowin': ['453815'],
  'Lubin Joakim': ['457111'],
  u'L\xe9onie-Dupouy': ['456690'],
  'Maela-Auguste': ['456651'],
  'Maela-auguste': ['456651'],
  'Maelle': ['454341'],
  u'Maena Lamolere\u2014Phelep': ['457961'],
  'Mame-Diop': ['462309'],
  'Manon-RHODE': ['458667'],
  'Manon-freyche': ['457558'],
  'Mathieu-Monteille': ['454079'],
  'Mathilde Bessonart': ['457173'],
  'Mathilde Majerus': ['458207'],
  u'Ma\xe9ly-LE TOUARIN CARVALHO': ['457714'],
  u'Ma\xe9ly.LeTouarinCarvalho': ['457714'],
  u'Ma\xebna -Lamol\xe8re Phelep': ['457961'],
  'Mignardot-Tiphaine': ['456686'],
  u'M\xe9lanie Lassagne': ['430746'],
  u'M\xe9lanie.lassagne': ['430746'],
  u'M\xe9li-Riaud.Juliette-Camut': ['450931', '446384'],
  u'M\xe9lissandre-Riaud': ['450931'],
  'Nassim Zahi': ['460525'],
  'Nicolo Farris - Giulia Nisini': ['463519', '463562'],
  'Nina callede , roxane Sais': ['458609', '455153'],
  u'Nina callede, roxane Sa\xefs': ['458609', '455153'],
  'Oceane-defreitas': ['458657'],
  u'Ome\xefma': ['416701'],
  u'Ome\xefma-Bourema': ['416701'],
  'Pagnoux Albanne': ['460344'],
  'Pagnoux-Pellegrino-Albanne': ['460344'],
  'Prep-prep': ['459660'],
  'Rhode-Manon': ['458667'],
  'Roxane sais, nina callede': ['455153', '458609'],
  'Roxane,Nina': ['455153', '458609'],
  'Sannah MAURINIER': ['460392'],
  u'Sema': ['456710'],
  'Sema-Canli': ['456710'],
  'Simone_PRISCA_VAVY': ['462574'],
  'Simone_prisca_vavy': ['462574'],
  'Timothee carrasset': ['455667'],
  'Timothee-carrasset': ['455667'],
  'Tiphaine Mignardot': ['456686'],
  'Tiphaine-Mignardot': ['456686'],
  'Victoria-Delhay Lucia-Pelanne': ['458356', '458010'],
  'Victoria-delhay': ['458356'],
  'Victoria-delhay Lucia-Pelanne': ['458356', '458010'],
  'Yuna-Gicquel': ['456846'],
  'Yuna-Gicquel. Adelie-almon': ['456846', '459692'],
  u'Yuna-Gicquel. Ad\xe9lie.Almon': ['456846', '459692'],
  u'Yuna-Gicquel.Ad\xe9lie-Almon': ['456846', '459692'],
  'albon lwann': ['396581'],
  'anais - bonetbelts': ['454875'],
  'anais-manus': ['457731'],
  'anais.bonetbelts': ['454875'],
  'camille-pelloquin': ['456868'],
  u'chlo\xe9-artola': ['458613'],
  'elisa-specogna': ['458747'],
  'hortense': ['458329'],
  'hortense-delacou': ['458329'],
  'ingrid fletcher': ['463523'],
  'jeane gabaston': ['460874'],
  'justine-loustaunau': ['459959'],
  'lana': ['460037'],
  'lena-erc': ['460829'],
  'lily barbry': ['457795'],
  'louhane-crowin': ['453815'],
  'louise dutheil': ['449639'],
  'louise-laveau': ['457952'],
  u'louise-laveau m\xe9lanie.lassagne': ['457952', '430746'],
  'louise.laveau': ['457952'],
  'lucie riviere': ['441018'],
  'lwann-albon': ['396581'],
  'maela-auguste': ['456651'],
  'maela.auguste': ['456651'],
  'manon-olivier': ['454852'],
  'melissa-johannet': ['455719'],
  'milena-hamilton': ['452779'],
  'mintou_ndiaye': ['460169'],
  u'n\xe9lia-agletiner': ['458113'],
  'rihanna - lair': ['456402'],
  u'roxane Sa\xefs, Nina callede': ['455153', '458609'],
  'sarah guellil': ['461900'],
  'sarah-guellil': ['461900'],
  'sema': ['456710'],
  'timothee-carrasset': ['455667'],
  'timothy andrade': ['414295'],
  'timothy-andradE': ['414295'],
  'timothy-andrade': ['414295'],
  u'timoth\xe9e-carrasset': ['455667'],
  'victoria-delhay': ['458356'],
  u'zo\xe9-marostica': ['453892'],
  u'\xe9lisa-coureau': ['459406'],
  u'\xe9lisa-coureau. manon-rhode': ['459406', '458667'],
  u'\xe9lisa_coureau': ['459406']},
 'etu2alias': {'396581': ['albon lwann', 'lwann-albon'],
  '414295': ['timothy-andrade', 'timothy-andradE', 'timothy andrade'],
  '416701': [u'Ome\xefma', u'Ome\xefma-Bourema'],
  '430746': [u'louise-laveau m\xe9lanie.lassagne',
   u'M\xe9lanie Lassagne',
   u'M\xe9lanie.lassagne'],
  '434036': ['Ahcene'],
  '441018': ['lucie riviere'],
  '446384': [u'M\xe9li-Riaud.Juliette-Camut',
   u'Ad\xe9lie Almon-Juliette Camut',
   'Juliette-camut Lila-Capraja',
   u'Ad\xe9lie-Almon Juliette-Camut',
   u'Juliette-camut M\xe9li-riaud',
   'Juliette-camut'],
  '447671': ['GUETATFA Ilhem'],
  '449639': ['louise dutheil'],
  '450931': [u'M\xe9li-Riaud.Juliette-Camut',
   u'Juliette-camut M\xe9li-riaud',
   u'M\xe9lissandre-Riaud'],
  '452779': ['milena-hamilton'],
  '453211': ['Charlotte-mariagecornille'],
  '453789': [u'Chlo\xe9- Cartigny'],
  '453815': [u'Louhane.crowin', 'louhane-crowin'],
  '453892': [u'zo\xe9-marostica'],
  '453951': [u'Ana\xebl'],
  '454079': ['Mathieu-Monteille'],
  '454341': ['Maelle'],
  '454852': ['manon-olivier'],
  '454875': ['anais.bonetbelts', 'anais - bonetbelts'],
  '455153': ['Roxane,Nina',
   u'roxane Sa\xefs, Nina callede',
   'Nina callede , roxane Sais',
   'Roxane sais, nina callede',
   u'Nina callede, roxane Sa\xefs'],
  '455667': ['Timothee-carrasset',
   'timothee-carrasset',
   u'timoth\xe9e-carrasset',
   'Timothee carrasset'],
  '455719': ['melissa-johannet'],
  '456402': ['rihanna - lair'],
  '456651': ['Maela-Auguste',
   'maela-auguste',
   'Maela-auguste',
   'maela.auguste'],
  '456672': ['Fevre Faustine'],
  '456686': ['Tiphaine-Mignardot', 'Mignardot-Tiphaine', 'Tiphaine Mignardot'],
  '456690': [u'L\xe9onie-Dupouy', 'Leonie Dupuy', 'Dupouy-Leonie'],
  '456710': ['sema', 'Sema-Canli', u'Sema'],
  '456846': [u'Yuna-Gicquel. Ad\xe9lie.Almon',
   u'Yuna-Gicquel.Ad\xe9lie-Almon',
   'Yuna-Gicquel',
   'Yuna-Gicquel. Adelie-almon'],
  '456868': ['camille-pelloquin'],
  '457111': ['Joakim-Lubin', 'Lubin Joakim'],
  '457173': ['Mathilde Bessonart'],
  '457483': ['Elisa Lucante'],
  '457558': ['Manon-freyche'],
  '457714': [u'Ma\xe9ly.LeTouarinCarvalho', u'Ma\xe9ly-LE TOUARIN CARVALHO'],
  '457731': ['anais-manus', 'Anais-manus'],
  '457795': ['lily barbry'],
  '457952': [u'louise-laveau m\xe9lanie.lassagne',
   'louise.laveau',
   'louise-laveau'],
  '457961': [u'Maena Lamolere\u2014Phelep', u'Ma\xebna -Lamol\xe8re Phelep'],
  '457965': ['Juliette-camut Lila-Capraja', 'Lila-Capraja'],
  '458010': ['Victoria-Delhay Lucia-Pelanne',
   'Emma darricau-Delhay- Pelanne',
   'Victoria-delhay Lucia-Pelanne'],
  '458113': [u'n\xe9lia-agletiner'],
  '458207': ['Mathilde Majerus',
   'EleonorecourtotMathildemajerus',
   'Eleonore/mathildemajerus'],
  '458313': ['Emma Darricau',
   'Emma darricau',
   'Elisa-Specogna,  emma darricau',
   'Emma darricau-Delhay- Pelanne'],
  '458324': ['Elisa Lavielle'],
  '458329': ['hortense-delacou', 'hortense'],
  '458356': ['Victoria-Delhay Lucia-Pelanne',
   'victoria-delhay',
   'Victoria-delhay',
   'Emma darricau-Delhay- Pelanne',
   'Victoria-delhay Lucia-Pelanne'],
  '458391': [u'Ala\xefa / Le\xefla', u'Ala\xefa RD / Le\xefla Facon'],
  '458551': [u'Ala\xefa Robin Deguil',
   u'Ala\xefa',
   u'Ala\xefa / Le\xefla',
   u'Ala\xefa RD / Le\xefla Facon'],
  '458609': ['Roxane,Nina',
   u'roxane Sa\xefs, Nina callede',
   'Nina callede , roxane Sais',
   'Roxane sais, nina callede',
   u'Nina callede, roxane Sa\xefs'],
  '458613': [u'chlo\xe9-artola'],
  '458657': ['Oceane-defreitas'],
  '458667': [u'\xe9lisa-coureau. manon-rhode', 'Rhode-Manon', 'Manon-RHODE'],
  '458727': ['Lina-Bourchachene'],
  '458747': ['Elisa Specogna',
   'Elisa-Specogna,  emma darricau',
   'elisa-specogna',
   'Elisa-Specogna'],
  '458790': [u'Andr\xe9a'],
  '459136': ['EleonorecourtotMathildemajerus',
   'Eleonore/mathildemajerus',
   'Eleonore Courtot'],
  '459406': [u'\xe9lisa-coureau. manon-rhode',
   u'\xe9lisa_coureau',
   u'\xe9lisa-coureau'],
  '459660': [u'B\xe9a', 'Prep-prep'],
  '459692': [u'Ad\xe9lie Almon-Juliette Camut',
   u'Yuna-Gicquel. Ad\xe9lie.Almon',
   u'Ad\xe9lie-Almon Juliette-Camut',
   u'Yuna-Gicquel.Ad\xe9lie-Almon',
   u'Ad\xe9lie-Almon',
   u'Ad\xe9lie Qlmon',
   'Yuna-Gicquel. Adelie-almon'],
  '459959': ['justine-loustaunau'],
  '459971': [u'J\xe9r\xe9mie Dubois', u'J\xe9r\xe9mie-Dubois'],
  '460037': ['lana'],
  '460084': [u'Copp\xe9lia-SEYDI', u'Copp\xe9lia SEYDI', u'Copp\xe9lia seydi'],
  '460169': ['mintou_ndiaye'],
  '460344': ['Albanne Pagnoux-Pellegrino',
   'Pagnoux Albanne',
   'Pagnoux-Pellegrino-Albanne'],
  '460392': ['Sannah MAURINIER'],
  '460488': [u'Ad\xe8le.Stidler', u'Ad\xe8le-stidler'],
  '460525': ['Nassim Zahi'],
  '460829': ['lena-erc'],
  '460874': ['jeane gabaston'],
  '461104': ['Julia-Anoge-Elsa-Dumas'],
  '461325': ['Julia-Anoge-Elsa-Dumas'],
  '461847': ['Kameron rouyat'],
  '461900': ['sarah guellil', 'sarah-guellil'],
  '462309': ['Mame-Diop'],
  '462574': ['Simone_PRISCA_VAVY', 'Simone_prisca_vavy'],
  '463519': ['Nicolo Farris - Giulia Nisini'],
  '463523': ['ingrid fletcher'],
  '463562': ['Giulia Nisini', 'Nicolo Farris - Giulia Nisini'],
  '463682': ['Elisa-Fougere']}}

In [172]:
with codecs.open(fAliasQDLE, 'w', encoding="utf8") as outfile:
    yaml.safe_dump(correspondances, outfile, default_flow_style=False)

# Calcul des notes
Attention au nombre de questions

In [173]:
nbQuestions=[7,7,7,7,7,7,7,6,6,6,6]
# nbQuestions=[7,7,7,7,7,7,6,6,6,6,6]
nbQ=float(nbQuestions[nQuizz-1])
print nbQ

6.0

In [174]:
def aliasQuizz(pseudo):
    result=None
    if pseudo in alias:
        result=alias[pseudo]
    return result

def noteQuizz(points):   
    result=8
    if points>0:
        result=int(round(10*(1+points/nbQ),0))
    return result
        
        

lQuizz["id"]=lQuizz["pseudo"].apply(aliasQuizz)
lQuizz["note"]=lQuizz["points"].apply(noteQuizz)

In [175]:
def splitPseudo1(id):
    result=None
    if id and len(id)>0:
        result=id[0]
    return result

def splitPseudo2(id):
    result=None
    if id and len(id)>1:
        result=id[1]
    return result

def splitPseudo3(id):
    result=None
    if id and len(id)>2:
        result=id[2]
    return result

lQuizz["id1"]=lQuizz["id"].apply(splitPseudo1)
lQuizz["id2"]=lQuizz["id"].apply(splitPseudo2)
lQuizz["id3"]=lQuizz["id"].apply(splitPseudo3)

lQuizz

,pseudo,points,temps,id,note,id1,id2,id3
0,maela.auguste,5,231.72,[456651],18,456651,None,None
1,chloé-artola,4,95.76,[458613],17,458613,None,None
2,manon-olivier,4,183.72,[454852],17,454852,None,None
3,anais-manus,4,194.88,[457731],17,457731,None,None
4,Juliette-camut,3,89.69,[446384],15,446384,None,None
5,Mélissandre-Riaud,3,140.87,[450931],15,450931,None,None
6,Dupouy-Leonie,3,141.59,[456690],15,456690,None,None
7,Yuna-Gicquel,3,170.55,[456846],15,456846,None,None
8,Alaïa,3,192.26,[458551],15,458551,None,None
9,Lubin Joakim,3,214.01,[457111],15,457111,None,None
10,Elisa Lucante,3,228.85,[457483],15,457483,None,None
11,timothy-andrade,3,251.98,[414295],15,414295,None,None
12,Chloé- Cartigny,2,45.86,[453789],13,453789,None,None
13,Adélie-Almon,2,88.27,[459692],13,459692,None,None
14,Adèle.Stidler,2,164.30,[460488],13,460488,None,None
15,nélia-agletiner,2,172.07,[458113],13,458113,None,None
16,Sema,2,172.83,[456710],13,456710,None,None
17,Victoria-Delhay Lucia-Pelanne,2,180.16,"[458356, 458010]",13,458356,458010,None
18,Mélanie Lassagne,2,185.01,[430746],13,430746,None,None
19,Emma darricau,2,207.49,[458313],13,458313,None,None
20,hortense-delacou,2,238.89,[458329],13,458329,None,None
21,anais.bonetbelts,1,101.24,[454875],12,454875,None,None
22,albon lwann,1,119.11,[396581],12,396581,None,None
23,Prep-prep,1,140.77,[459660],12,459660,None,None
24,Coppélia-SEYDI,1,149.45,[460084],12,460084,None,None
25,Maena Lamolere—Phelep,1,152.01,[457961],12,457961,None,None
26,louise.laveau,1,178.67,[457952],12,457952,None,None
27,Charlotte-mariagecornille,1,200.10,[453211],12,453211,None,None
28,Jérémie Dubois,1,225.36,[459971],12,459971,None,None
29,milena-hamilton,1,245.90,[452779],12,452779,None,None
30,Mélanie,0,0.00,None,8,None,None,None
31,Ahcene,0,83.55,[434036],8,434036,None,None
32,Elisa Specogna,0,93.55,[458747],8,458747,None,None
33,Louhane.crowin,0,140.00,[453815],8,453815,None,None
34,melissa-johannet,0,186.60,[455719],8,455719,None,None

In [176]:
df1=lQuizz[["pseudo","note","temps","id1"]].dropna()
df2=lQuizz[["pseudo","note","temps","id2"]].dropna()
df3=lQuizz[["pseudo","note","temps","id3"]].dropna()
df1.columns=["pseudo","note","temps","id"]
df2.columns=["pseudo","note","temps","id"]
df3.columns=["pseudo","note","temps","id"]

In [177]:
df123=pd.concat([df1,df2,df3]).sort_values(["note","temps"],ascending=[False,True]).reset_index(drop=True)
df123

                           pseudo  note   temps      id
0                   maela.auguste    18  231.72  456651
1                    chloé-artola    17   95.76  458613
2                   manon-olivier    17  183.72  454852
3                     anais-manus    17  194.88  457731
4                  Juliette-camut    15   89.69  446384
5               Mélissandre-Riaud    15  140.87  450931
6                   Dupouy-Leonie    15  141.59  456690
7                    Yuna-Gicquel    15  170.55  456846
8                           Alaïa    15  192.26  458551
9                    Lubin Joakim    15  214.01  457111
10                  Elisa Lucante    15  228.85  457483
11                timothy-andrade    15  251.98  414295
12                Chloé- Cartigny    13   45.86  453789
13                   Adélie-Almon    13   88.27  459692
14                  Adèle.Stidler    13  164.30  460488
15                nélia-agletiner    13  172.07  458113
16                           Sema    13  172.83  456710
17  Victoria-Delhay Lucia-Pelanne    13  180.16  458356
18  Victoria-Delhay Lucia-Pelanne    13  180.16  458010
19               Mélanie Lassagne    13  185.01  430746
20                  Emma darricau    13  207.49  458313
21               hortense-delacou    13  238.89  458329
22               anais.bonetbelts    12  101.24  454875
23                    albon lwann    12  119.11  396581
24                      Prep-prep    12  140.77  459660
25                 Coppélia-SEYDI    12  149.45  460084
26          Maena Lamolere—Phelep    12  152.01  457961
27                  louise.laveau    12  178.67  457952
28      Charlotte-mariagecornille    12  200.10  453211
29                 Jérémie Dubois    12  225.36  459971
30                milena-hamilton    12  245.90  452779
31                         Ahcene     8   83.55  434036
32                 Elisa Specogna     8   93.55  458747
33                 Louhane.crowin     8  140.00  453815
34               melissa-johannet     8  186.60  455719

In [178]:
df123.loc[(df123.note==8)&(df123.temps>0),"note"]=10

In [179]:
df123.head()

           pseudo  note   temps      id
0   maela.auguste    18  231.72  456651
1    chloé-artola    17   95.76  458613
2   manon-olivier    17  183.72  454852
3     anais-manus    17  194.88  457731
4  Juliette-camut    15   89.69  446384

In [180]:
if df123.loc[0,'pseudo']==df123.loc[1,'pseudo']:
    df123.at[0,'note'] = 20
    df123.at[1,'note'] = 20
    if df123.loc[2,'pseudo']==df123.loc[3,'pseudo']:
        if df123.loc[2, "note"]<18:
            df123.at[2, 'note'] = 18
            df123.at[3, 'note'] = 18
    else:
        if df123.loc[2, "note"]<18:
            df123.at[2, 'note'] = 18
else:        
    df123.at[0,'note'] = 20
    if df123.loc[1,'pseudo']==df123.loc[2,'pseudo']:
        if df123.loc[1, "note"]<18:
            df123.at[1, 'note'] = 18
            df123.at[2, 'note'] = 18
    else:
        if df123.loc[1, "note"]<18:
            df123.at[1, 'note'] = 18
df123

                           pseudo  note   temps      id
0                   maela.auguste    20  231.72  456651
1                    chloé-artola    18   95.76  458613
2                   manon-olivier    17  183.72  454852
3                     anais-manus    17  194.88  457731
4                  Juliette-camut    15   89.69  446384
5               Mélissandre-Riaud    15  140.87  450931
6                   Dupouy-Leonie    15  141.59  456690
7                    Yuna-Gicquel    15  170.55  456846
8                           Alaïa    15  192.26  458551
9                    Lubin Joakim    15  214.01  457111
10                  Elisa Lucante    15  228.85  457483
11                timothy-andrade    15  251.98  414295
12                Chloé- Cartigny    13   45.86  453789
13                   Adélie-Almon    13   88.27  459692
14                  Adèle.Stidler    13  164.30  460488
15                nélia-agletiner    13  172.07  458113
16                           Sema    13  172.83  456710
17  Victoria-Delhay Lucia-Pelanne    13  180.16  458356
18  Victoria-Delhay Lucia-Pelanne    13  180.16  458010
19               Mélanie Lassagne    13  185.01  430746
20                  Emma darricau    13  207.49  458313
21               hortense-delacou    13  238.89  458329
22               anais.bonetbelts    12  101.24  454875
23                    albon lwann    12  119.11  396581
24                      Prep-prep    12  140.77  459660
25                 Coppélia-SEYDI    12  149.45  460084
26          Maena Lamolere—Phelep    12  152.01  457961
27                  louise.laveau    12  178.67  457952
28      Charlotte-mariagecornille    12  200.10  453211
29                 Jérémie Dubois    12  225.36  459971
30                milena-hamilton    12  245.90  452779
31                         Ahcene    10   83.55  434036
32                 Elisa Specogna    10   93.55  458747
33                 Louhane.crowin    10  140.00  453815
34               melissa-johannet    10  186.60  455719

In [181]:
dfNotes=df123.groupby("id").max().sort_values("note",ascending=False)
dfNotes.to_csv(fNotes,sep="\t",encoding="utf8")

In [182]:
dfNotes

                               pseudo  note   temps
id
456651                  maela.auguste    20  231.72
458613                   chloé-artola    18   95.76
457731                    anais-manus    17  194.88
454852                  manon-olivier    17  183.72
457111                   Lubin Joakim    15  214.01
457483                  Elisa Lucante    15  228.85
456846                   Yuna-Gicquel    15  170.55
456690                  Dupouy-Leonie    15  141.59
414295                timothy-andrade    15  251.98
458551                          Alaïa    15  192.26
450931              Mélissandre-Riaud    15  140.87
446384                 Juliette-camut    15   89.69
458329               hortense-delacou    13  238.89
458356  Victoria-Delhay Lucia-Pelanne    13  180.16
458113                nélia-agletiner    13  172.07
458010  Victoria-Delhay Lucia-Pelanne    13  180.16
459692                   Adélie-Almon    13   88.27
458313                  Emma darricau    13  207.49
460488                  Adèle.Stidler    13  164.30
456710                           Sema    13  172.83
453789                Chloé- Cartigny    13   45.86
430746               Mélanie Lassagne    13  185.01
457952                  louise.laveau    12  178.67
457961          Maena Lamolere—Phelep    12  152.01
454875               anais.bonetbelts    12  101.24
453211      Charlotte-mariagecornille    12  200.10
452779                milena-hamilton    12  245.90
459660                      Prep-prep    12  140.77
459971                 Jérémie Dubois    12  225.36
460084                 Coppélia-SEYDI    12  149.45
396581                    albon lwann    12  119.11
455719               melissa-johannet    10  186.60
453815                 Louhane.crowin    10  140.00
434036                         Ahcene    10   83.55
458747                 Elisa Specogna    10   93.55